/**
 * Badge component generator.
 * Generates a typed, accessible React Badge component for status labels and counts.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateBadge(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const variants = rule?.allowedVariants ?? [
    "default",
    "success",
    "warning",
    "danger",
    "info",
  ];
  const variantType = variants.map((v) => `"${v}"`).join(" | ");

  return `/**
 * Badge — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 * Allowed variants: ${variants.join(", ")}
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type BadgeVariant = ${variantType};
export type BadgeSize = "sm" | "md" | "lg";

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  /** Visual style variant */
  variant?: BadgeVariant;
  /** Size preset */
  size?: BadgeSize;
  /** Renders as a dot with no text */
  dot?: boolean;
  children?: React.ReactNode;
}

// ─── Size styles ──────────────────────────────────────────────────────────────

const SIZE_STYLES: Record<BadgeSize, React.CSSProperties> = {
  sm: {
    fontSize: "var(--font-size-caption, 0.75rem)",
    padding: "1px var(--spacing-1, 4px)",
    lineHeight: "var(--line-height-caption, 1.4)",
  },
  md: {
    fontSize: "var(--font-size-small, 0.875rem)",
    padding: "2px var(--spacing-2, 8px)",
    lineHeight: "var(--line-height-body, 1.5)",
  },
  lg: {
    fontSize: "var(--font-size-body, 1rem)",
    padding: "var(--spacing-1, 4px) var(--spacing-3, 12px)",
    lineHeight: "var(--line-height-body, 1.5)",
  },
};

// ─── Variant styles ───────────────────────────────────────────────────────────

const VARIANT_STYLES: Record<BadgeVariant, React.CSSProperties> = {
  default: {
    background: "var(--badge-bg-default, var(--color-bg-subtle, #f1f5f9))",
    color: "var(--badge-text-default, var(--color-text-secondary, #6b7280))",
  },
  success: {
    background: "var(--badge-bg-success, var(--color-success-subtle, #dcfce7))",
    color: "var(--badge-text-success, var(--color-success-fg, #16a34a))",
  },
  warning: {
    background: "var(--badge-bg-warning, var(--color-warning-subtle, #fef9c3))",
    color: "var(--badge-text-warning, var(--color-warning-fg, #ca8a04))",
  },
  danger: {
    background: "var(--badge-bg-danger, var(--color-danger-subtle, #fee2e2))",
    color: "var(--badge-text-danger, var(--color-danger-fg, #dc2626))",
  },
  info: {
    background: "var(--badge-bg-info, var(--color-info-subtle, #dbeafe))",
    color: "var(--badge-text-info, var(--color-info-fg, #2563eb))",
  },
};

// ─── Component ────────────────────────────────────────────────────────────────

export function Badge({
  variant = "default",
  size = "md",
  dot = false,
  children,
  style,
  ...props
}: BadgeProps) {
  const baseStyle: React.CSSProperties = {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "var(--font-family-base, inherit)",
    fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
    borderRadius: "var(--badge-radius, var(--radius-full, 9999px))",
    whiteSpace: "nowrap",
    userSelect: "none",
    ...(dot
      ? {
          width: "var(--spacing-2, 8px)",
          height: "var(--spacing-2, 8px)",
          padding: 0,
          borderRadius: "50%",
        }
      : SIZE_STYLES[size]),
    ...VARIANT_STYLES[variant],
    ...style,
  };

  return (
    <span style={baseStyle} {...props}>
      {!dot && children}
    </span>
  );
}

Badge.displayName = "Badge";
`;
}
