/**
 * Button component generator.
 *
 * Generates a fully typed, accessible React Button component
 * using CSS custom properties for all visual tokens.
 * Variant types and governance rules are derived from design-system.rules.json.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateButton(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const variants = rule?.allowedVariants ?? [
    "primary",
    "secondary",
    "danger",
    "ghost",
  ];
  const requiresAriaLabel = rule?.a11y?.ariaLabel === "required";
  const maxWidth = rule?.maxWidth ?? "none";

  const variantType = variants.map((v) => `"${v}"`).join(" | ");
  const variantStyles = generateVariantStyles(variants, config);

  return `/**
 * Button — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 * Allowed variants: ${variants.join(", ")}
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type ButtonVariant = ${variantType};
export type ButtonSize = "sm" | "md" | "lg";

export interface ButtonProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "aria-label"> {
  /** Visual style variant */
  variant?: ButtonVariant;
  /** Size preset */
  size?: ButtonSize;
  /** Shows a loading spinner and disables interaction */
  loading?: boolean;
  /** Full-width block button */
  fullWidth?: boolean;
  /** Left icon slot */
  iconLeft?: React.ReactNode;
  /** Right icon slot */
  iconRight?: React.ReactNode;
  /**
   * Accessible label.${requiresAriaLabel ? "\n   * @required Governance rule: buttons must have aria-label." : ""}
   */
  "aria-label": string;
  children?: React.ReactNode;
}

// ─── Size styles ──────────────────────────────────────────────────────────────

const SIZE_STYLES: Record<ButtonSize, React.CSSProperties> = {
  sm: {
    fontSize: "var(--font-size-small, 0.875rem)",
    padding: "var(--spacing-2, 8px) var(--spacing-3, 12px)",
    gap: "var(--spacing-1, 4px)",
  },
  md: {
    fontSize: "var(--font-size-body, 1rem)",
    padding: "var(--component-padding-sm, 8px) var(--component-padding-md, 16px)",
    gap: "var(--spacing-2, 8px)",
  },
  lg: {
    fontSize: "var(--font-size-body, 1rem)",
    padding: "var(--component-padding-md, 16px) var(--spacing-6, 32px)",
    gap: "var(--spacing-2, 8px)",
  },
};

// ─── Variant styles ───────────────────────────────────────────────────────────
${variantStyles}

// ─── Component ────────────────────────────────────────────────────────────────

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  function Button(
    {
      variant = "primary",
      size = "md",
      loading = false,
      fullWidth = false,
      iconLeft,
      iconRight,
      disabled,
      children,
      style,
      ...props
    },
    ref,
  ) {
    const isDisabled = disabled ?? loading;

    const baseStyle: React.CSSProperties = {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      fontFamily: "var(--font-family-base, inherit)",
      fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
      lineHeight: 1,
      border: "1px solid transparent",
      borderRadius: "var(--button-radius, var(--radius-md, 4px))",
      cursor: isDisabled ? "not-allowed" : "pointer",
      opacity: isDisabled ? "var(--state-disabled-opacity, 0.4)" : 1,
      transition: [
        "background-color var(--duration-fast, 100ms) var(--easing-standard, ease)",
        "border-color var(--duration-fast, 100ms) var(--easing-standard, ease)",
        "box-shadow var(--duration-fast, 100ms) var(--easing-standard, ease)",
        "opacity var(--duration-fast, 100ms)",
      ].join(", "),
      maxWidth: "${maxWidth}",
      width: fullWidth ? "100%" : undefined,
      outline: "none",
      textDecoration: "none",
      whiteSpace: "nowrap",
      userSelect: "none",
      ...SIZE_STYLES[size],
      ...VARIANT_STYLES[variant],
      ...style,
    };

    const focusStyle: React.CSSProperties = {
      boxShadow: [
        "0 0 0 var(--focus-ring-offset, 2px) var(--color-bg-default, #fff)",
        "0 0 0 calc(var(--focus-ring-offset, 2px) + var(--focus-ring-width, 2px)) var(--focus-ring-color, #2563eb)",
      ].join(", "),
    };

    const [isFocusVisible, setIsFocusVisible] = React.useState(false);

    const handleKeyUp = () => setIsFocusVisible(true);
    const handleMouseDown = () => setIsFocusVisible(false);
    const handleBlur = () => setIsFocusVisible(false);

    return (
      <button
        ref={ref}
        disabled={isDisabled}
        style={{ ...baseStyle, ...(isFocusVisible ? focusStyle : {}) }}
        onKeyUp={handleKeyUp}
        onMouseDown={handleMouseDown}
        onBlur={handleBlur}
        {...props}
      >
        {loading && (
          <LoadingSpinner
            size={size === "sm" ? 14 : 16}
            aria-hidden="true"
          />
        )}
        {!loading && iconLeft && <span aria-hidden="true">{iconLeft}</span>}
        {children && <span>{children}</span>}
        {!loading && iconRight && <span aria-hidden="true">{iconRight}</span>}
      </button>
    );
  },
);

Button.displayName = "Button";

// ─── Loading spinner ──────────────────────────────────────────────────────────

function LoadingSpinner({ size, ...props }: { size: number } & React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      style={{
        animation: "dsforge-spin 0.75s linear infinite",
      }}
      {...props}
    >
      <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
    </svg>
  );
}

// ─── Keyframe injection ───────────────────────────────────────────────────────

if (typeof document !== "undefined") {
  const styleId = "dsforge-button-keyframes";
  if (!document.getElementById(styleId)) {
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = "@keyframes dsforge-spin { to { transform: rotate(360deg); } }";
    document.head.appendChild(style);
  }
}
`;
}

// ─── Variant style generator ──────────────────────────────────────────────────

function generateVariantStyles(
  variants: string[],
  _config: DesignSystemConfig,
): string {
  const variantMap: Record<string, string> = {
    primary: `  primary: {
    background: "var(--button-bg, var(--color-action, #2563eb))",
    color: "var(--button-text, var(--color-text-inverse, #ffffff))",
    borderColor: "var(--button-bg, var(--color-action, #2563eb))",
  }`,
    secondary: `  secondary: {
    background: "var(--color-bg-subtle, #f8fafc)",
    color: "var(--color-text-primary, #111827)",
    borderColor: "var(--color-border-default, #e2e8f0)",
  }`,
    danger: `  danger: {
    background: "var(--color-danger-fg, #dc2626)",
    color: "#ffffff",
    borderColor: "var(--color-danger-fg, #dc2626)",
  }`,
    ghost: `  ghost: {
    background: "transparent",
    color: "var(--color-action, #2563eb)",
    borderColor: "transparent",
  }`,
    outline: `  outline: {
    background: "transparent",
    color: "var(--color-action, #2563eb)",
    borderColor: "var(--color-action, #2563eb)",
  }`,
  };

  const entries = variants.map((v) => {
    return variantMap[v] ?? `  ${v}: {}`;
  });

  return `
const VARIANT_STYLES: Record<ButtonVariant, React.CSSProperties> = {
${entries.join(",\n")},
};
`;
}
