/**
 * Card component generator.
 * Generates a composable Card with Header, Body, and Footer slots.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateCard(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const variants = rule?.allowedVariants ?? ["default", "elevated", "outlined"];
  const maxWidth = rule?.maxWidth ?? "none";
  const variantType = variants.map((v) => `"${v}"`).join(" | ");

  return `/**
 * Card — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 * Composable: use Card.Header, Card.Body, Card.Footer for structured content.
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type CardVariant = ${variantType};

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Visual style variant */
  variant?: CardVariant;
  /** Override max-width. Default: ${maxWidth} */
  maxWidth?: string | number;
  /** Remove all padding from the card body */
  noPadding?: boolean;
  children: React.ReactNode;
  /** Style overrides applied to the card container */
  style?: React.CSSProperties;
}

export interface CardSectionProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
  /** Style overrides applied to the section element */
  style?: React.CSSProperties;
}

// ─── Variant styles ───────────────────────────────────────────────────────────

const VARIANT_STYLES: Record<CardVariant, React.CSSProperties> = {
${generateVariantStylesCard(variants)}
};

// ─── Card ─────────────────────────────────────────────────────────────────────

function CardRoot({
  variant = "default",
  maxWidth: maxWidthProp,
  noPadding = false,
  style,
  children,
  ...props
}: CardProps) {
  const computedMaxWidth = maxWidthProp
    ? typeof maxWidthProp === "number"
      ? \`\${maxWidthProp}px\`
      : maxWidthProp
    : "${maxWidth}";

  const baseStyle: React.CSSProperties = {
    display: "flex",
    flexDirection: "column",
    background: "var(--card-bg, var(--color-bg-default, #ffffff))",
    borderRadius: "var(--card-radius, var(--radius-lg, 8px))",
    overflow: "hidden",
    maxWidth: computedMaxWidth,
    width: "100%",
    fontFamily: "var(--font-family-base, inherit)",
    transition: "box-shadow var(--duration-normal, 200ms) var(--easing-standard, ease)",
    ...VARIANT_STYLES[variant],
    ...style,
  };

  return (
    <div style={baseStyle} {...props}>
      {children}
    </div>
  );
}

// ─── Card.Header ──────────────────────────────────────────────────────────────

function CardHeader({ style, children, ...props }: CardSectionProps) {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "var(--component-padding-md, 16px)",
        borderBottom: "1px solid var(--color-border-default, #e2e8f0)",
        ...style,
      }}
      {...props}
    >
      {children}
    </div>
  );
}

// ─── Card.Body ────────────────────────────────────────────────────────────────

function CardBody({ style, children, ...props }: CardSectionProps) {
  return (
    <div
      style={{
        flex: 1,
        padding: "var(--component-padding-md, 16px)",
        color: "var(--color-text-primary, #111827)",
        fontSize: "var(--font-size-body, 1rem)",
        lineHeight: "var(--line-height-body, 1.5)",
        ...style,
      }}
      {...props}
    >
      {children}
    </div>
  );
}

// ─── Card.Footer ──────────────────────────────────────────────────────────────

function CardFooter({ style, children, ...props }: CardSectionProps) {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "var(--spacing-3, 12px)",
        padding: "var(--component-padding-md, 16px)",
        borderTop: "1px solid var(--color-border-default, #e2e8f0)",
        background: "var(--color-bg-subtle, #f8fafc)",
        ...style,
      }}
      {...props}
    >
      {children}
    </div>
  );
}

// ─── Composite export ─────────────────────────────────────────────────────────

export const Card = Object.assign(CardRoot, {
  Header: CardHeader,
  Body: CardBody,
  Footer: CardFooter,
});
`;
}

function generateVariantStylesCard(variants: string[]): string {
  const map: Record<string, string> = {
    default: `  default: {
    border: "1px solid var(--color-border-default, #e2e8f0)",
    boxShadow: "none",
  }`,
    elevated: `  elevated: {
    border: "1px solid transparent",
    boxShadow: "var(--shadow-2, 0 1px 3px 0 rgb(0 0 0 / 0.10))",
  }`,
    outlined: `  outlined: {
    border: "2px solid var(--color-border-strong, #94a3b8)",
    boxShadow: "none",
  }`,
    interactive: `  interactive: {
    border: "1px solid var(--color-border-default, #e2e8f0)",
    boxShadow: "var(--shadow-1, 0 1px 2px 0 rgb(0 0 0 / 0.05))",
    cursor: "pointer",
  }`,
  };

  return variants.map((v) => map[v] ?? `  ${v}: {}`).join(",\n");
}
