/**
 * Checkbox component generator.
 * Generates a typed, accessible React Checkbox with label and indeterminate support.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateCheckbox(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const requiresAriaLabel = rule?.a11y?.ariaLabel === "required";

  return `/**
 * Checkbox — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type" | "size" | "style"> {
  /** Visible label */
  label?: string;
  /** Helper text shown below the label */
  helperText?: string;
  /** Indeterminate state (partially checked) */
  indeterminate?: boolean;
  /** Size preset */
  size?: "sm" | "md" | "lg";
  /** Style applied to the outer wrapper element */
  style?: React.CSSProperties;${requiresAriaLabel ? '\n  /** @required Governance rule: checkboxes must have aria-label. */\n  "aria-label": string;' : '\n  "aria-label"?: string;'}
}

// ─── Size map ─────────────────────────────────────────────────────────────────

const SIZE_BOX: Record<"sm" | "md" | "lg", string> = {
  sm: "14px",
  md: "16px",
  lg: "20px",
};

const SIZE_FONT: Record<"sm" | "md" | "lg", string> = {
  sm: "var(--font-size-caption, 0.75rem)",
  md: "var(--font-size-small, 0.875rem)",
  lg: "var(--font-size-body, 1rem)",
};

// ─── Keyframe injection ───────────────────────────────────────────────────────

if (typeof document !== "undefined") {
  const styleId = "dsforge-checkbox-styles";
  if (!document.getElementById(styleId)) {
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = \`
      @keyframes dsforge-checkbox-check {
        from { stroke-dashoffset: 16; }
        to   { stroke-dashoffset: 0; }
      }
    \`;
    document.head.appendChild(style);
  }
}

// ─── Component ────────────────────────────────────────────────────────────────

export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  function Checkbox(
    {
      label,
      helperText,
      indeterminate = false,
      size = "md",
      disabled,
      checked,
      defaultChecked,
      style,
      id: propId,
      onChange,
      ...props
    },
    ref,
  ) {
    const id = propId ?? React.useId();
    const helperId = \`\${id}-helper\`;
    const internalRef = React.useRef<HTMLInputElement>(null);
    React.useImperativeHandle(ref, () => internalRef.current!);

    const [isChecked, setIsChecked] = React.useState(defaultChecked ?? false);
    const [isFocusVisible, setIsFocusVisible] = React.useState(false);

    const controlled = checked !== undefined;
    const resolvedChecked = controlled ? checked : isChecked;
    const boxSize = SIZE_BOX[size];

    React.useEffect(() => {
      if (internalRef.current) {
        internalRef.current.indeterminate = indeterminate;
      }
    }, [indeterminate]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      if (!controlled) setIsChecked(e.target.checked);
      onChange?.(e);
    };

    const isActive = resolvedChecked || indeterminate;

    const boxStyle: React.CSSProperties = {
      width: boxSize,
      height: boxSize,
      flexShrink: 0,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "var(--checkbox-radius, var(--radius-sm, 2px))",
      border: \`2px solid \${
        isActive
          ? "var(--checkbox-color, var(--color-action, #2563eb))"
          : "var(--checkbox-border, var(--color-border-default, #e2e8f0))"
      }\`,
      background: isActive
        ? "var(--checkbox-color, var(--color-action, #2563eb))"
        : "var(--checkbox-bg, var(--color-bg-default, #ffffff))",
      transition: \`background var(--duration-fast, 100ms), border-color var(--duration-fast, 100ms)\`,
      boxShadow: isFocusVisible
        ? [
            "0 0 0 var(--focus-ring-offset, 2px) var(--color-bg-default, #fff)",
            "0 0 0 calc(var(--focus-ring-offset, 2px) + var(--focus-ring-width, 2px)) var(--focus-ring-color, #2563eb)",
          ].join(", ")
        : undefined,
      pointerEvents: "none",
    };

    return (
      <div
        style={{
          display: "inline-flex",
          flexDirection: "column",
          gap: "var(--spacing-1, 4px)",
          opacity: disabled ? "var(--state-disabled-opacity, 0.4)" : 1,
          cursor: disabled ? "not-allowed" : "default",
          fontFamily: "var(--font-family-base, inherit)",
          ...style,
        }}
      >
        <label
          htmlFor={id}
          style={{
            display: "inline-flex",
            alignItems: "flex-start",
            gap: "var(--spacing-2, 8px)",
            cursor: disabled ? "not-allowed" : "pointer",
          }}
        >
          {/* Hidden native input */}
          <input
            ref={internalRef}
            type="checkbox"
            id={id}
            checked={resolvedChecked}
            disabled={disabled}
            aria-describedby={helperText ? helperId : undefined}
            onChange={handleChange}
            onKeyUp={() => setIsFocusVisible(true)}
            onMouseDown={() => setIsFocusVisible(false)}
            onBlur={() => setIsFocusVisible(false)}
            style={{
              position: "absolute",
              opacity: 0,
              width: boxSize,
              height: boxSize,
              margin: 0,
              cursor: disabled ? "not-allowed" : "pointer",
            }}
            {...props}
          />

          {/* Custom visual box */}
          <span style={boxStyle} aria-hidden="true">
            {isActive && (
              <svg
                width={parseInt(boxSize) - 6}
                height={parseInt(boxSize) - 6}
                viewBox="0 0 10 10"
                fill="none"
                stroke="#fff"
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                {indeterminate ? (
                  <line x1="2" y1="5" x2="8" y2="5" />
                ) : (
                  <polyline
                    points="1.5,5 4,7.5 8.5,2.5"
                    style={{
                      strokeDasharray: 16,
                      strokeDashoffset: 0,
                      animation: "dsforge-checkbox-check 150ms ease forwards",
                    }}
                  />
                )}
              </svg>
            )}
          </span>

          {label && (
            <span
              style={{
                fontSize: SIZE_FONT[size],
                color: "var(--color-text-primary, #111827)",
                lineHeight: "var(--line-height-body, 1.5)",
                paddingTop: "1px",
              }}
            >
              {label}
            </span>
          )}
        </label>

        {helperText && (
          <span
            id={helperId}
            style={{
              fontSize: "var(--font-size-caption, 0.75rem)",
              color: "var(--color-text-secondary, #6b7280)",
              paddingLeft: \`calc(\${boxSize} + var(--spacing-2, 8px))\`,
            }}
          >
            {helperText}
          </span>
        )}
      </div>
    );
  },
);

Checkbox.displayName = "Checkbox";
`;
}
