/**
 * Input component generator.
 * Generates a typed, accessible React Input with label, error, and helper text slots.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateInput(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const variants = rule?.allowedVariants ?? ["default", "error", "disabled"];
  const variantType = variants.map((v) => `"${v}"`).join(" | ");

  return `/**
 * Input — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type InputVariant = ${variantType};

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "size" | "style"> {
  /** Visual/state variant */
  variant?: InputVariant;
  /** Label displayed above the input */
  label?: string;
  /** Helper text shown below the input */
  helperText?: string;
  /** Error message — also sets variant to "error" when present */
  errorMessage?: string;
  /** Size preset */
  size?: "sm" | "md" | "lg";
  /** Left adornment (icon or text) */
  startAdornment?: React.ReactNode;
  /** Right adornment (icon or text) */
  endAdornment?: React.ReactNode;
  /** Accessible label — required for inputs without a visible label */
  "aria-label"?: string;
  /** Style applied to the outer wrapper element */
  style?: React.CSSProperties;
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const SIZE_PADDING: Record<"sm" | "md" | "lg", string> = {
  sm: "var(--spacing-1, 4px) var(--spacing-2, 8px)",
  md: "var(--component-padding-sm, 8px) var(--component-padding-md, 16px)",
  lg: "var(--component-padding-md, 16px) var(--component-padding-lg, 24px)",
};

const SIZE_FONT: Record<"sm" | "md" | "lg", string> = {
  sm: "var(--font-size-small, 0.875rem)",
  md: "var(--font-size-body, 1rem)",
  lg: "var(--font-size-body, 1rem)",
};

// ─── Component ────────────────────────────────────────────────────────────────

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  function Input(
    {
      variant = "default",
      size = "md",
      label,
      helperText,
      errorMessage,
      startAdornment,
      endAdornment,
      style,
      id: propId,
      disabled,
      ...props
    },
    ref,
  ) {
    const id = propId ?? React.useId();
    const errorId = \`\${id}-error\`;
    const helperId = \`\${id}-helper\`;

    const hasError = Boolean(errorMessage);
    const isDisabled = disabled ?? variant === "disabled";
    const resolvedVariant: InputVariant = hasError ? "error" : variant;

    const borderColor =
      resolvedVariant === "error"
        ? "var(--color-danger-border, #fca5a5)"
        : "var(--input-border, var(--color-border-default, #e2e8f0))";

    const wrapperStyle: React.CSSProperties = {
      display: "flex",
      flexDirection: "column",
      gap: "var(--spacing-1, 4px)",
      fontFamily: "var(--font-family-base, inherit)",
      opacity: isDisabled ? "var(--state-disabled-opacity, 0.4)" : 1,
      ...style,
    };

    const inputWrapperStyle: React.CSSProperties = {
      display: "flex",
      alignItems: "center",
      background: "var(--input-bg, var(--color-bg-default, #ffffff))",
      border: \`1px solid \${borderColor}\`,
      borderRadius: "var(--input-radius, var(--radius-md, 4px))",
      transition: \`border-color var(--duration-fast, 100ms) var(--easing-standard, ease),
        box-shadow var(--duration-fast, 100ms) var(--easing-standard, ease)\`,
      cursor: isDisabled ? "not-allowed" : "text",
    };

    const inputStyle: React.CSSProperties = {
      flex: 1,
      padding: SIZE_PADDING[size],
      fontSize: SIZE_FONT[size],
      lineHeight: "var(--line-height-body, 1.5)",
      color: "var(--color-text-primary, #111827)",
      background: "transparent",
      border: "none",
      outline: "none",
      cursor: isDisabled ? "not-allowed" : "text",
    };

    const [isFocused, setIsFocused] = React.useState(false);

    const focusShadow = isFocused
      ? [
          "0 0 0 var(--focus-ring-offset, 2px) var(--color-bg-default, #fff)",
          "0 0 0 calc(var(--focus-ring-offset, 2px) + var(--focus-ring-width, 2px)) var(--focus-ring-color, #2563eb)",
        ].join(", ")
      : undefined;

    return (
      <div style={wrapperStyle}>
        {label && (
          <label
            htmlFor={id}
            style={{
              fontSize: "var(--font-size-label, 0.875rem)",
              fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
              color: "var(--color-text-primary, #111827)",
              lineHeight: "var(--line-height-label, 1.4)",
            }}
          >
            {label}
          </label>
        )}

        <div
          style={{
            ...inputWrapperStyle,
            boxShadow: focusShadow,
            borderColor: isFocused
              ? "var(--input-border-focus, var(--color-border-focus, #2563eb))"
              : borderColor,
          }}
        >
          {startAdornment && (
            <span
              aria-hidden="true"
              style={{
                display: "flex",
                alignItems: "center",
                paddingLeft: "var(--spacing-3, 12px)",
                color: "var(--color-text-secondary, #6b7280)",
                flexShrink: 0,
              }}
            >
              {startAdornment}
            </span>
          )}

          <input
            ref={ref}
            id={id}
            disabled={isDisabled}
            aria-invalid={hasError ? "true" : undefined}
            aria-describedby={
              [hasError ? errorId : null, helperText ? helperId : null]
                .filter(Boolean)
                .join(" ") || undefined
            }
            style={inputStyle}
            onFocus={() => setIsFocused(true)}
            onBlur={() => setIsFocused(false)}
            {...props}
          />

          {endAdornment && (
            <span
              aria-hidden="true"
              style={{
                display: "flex",
                alignItems: "center",
                paddingRight: "var(--spacing-3, 12px)",
                color: "var(--color-text-secondary, #6b7280)",
                flexShrink: 0,
              }}
            >
              {endAdornment}
            </span>
          )}
        </div>

        {hasError && (
          <span
            id={errorId}
            role="alert"
            style={{
              fontSize: "var(--font-size-caption, 0.75rem)",
              color: "var(--color-danger-fg, #dc2626)",
              lineHeight: "var(--line-height-caption, 1.4)",
            }}
          >
            {errorMessage}
          </span>
        )}

        {helperText && !hasError && (
          <span
            id={helperId}
            style={{
              fontSize: "var(--font-size-caption, 0.75rem)",
              color: "var(--color-text-secondary, #6b7280)",
              lineHeight: "var(--line-height-caption, 1.4)",
            }}
          >
            {helperText}
          </span>
        )}
      </div>
    );
  },
);

Input.displayName = "Input";
`;
}
