/**
 * Radio component generator.
 * Generates a typed, accessible React Radio and RadioGroup component.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateRadio(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const requiresAriaLabel = rule?.a11y?.ariaLabel === "required";

  return `/**
 * Radio — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 * Exports: Radio, RadioGroup
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface RadioProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type" | "size" | "style"> {
  /** Visible label */
  label?: string;
  /** Size preset */
  size?: "sm" | "md" | "lg";
  /** Style applied to the outer label wrapper */
  style?: React.CSSProperties;${requiresAriaLabel ? '\n  /** @required Governance rule: radio inputs must have aria-label. */\n  "aria-label": string;' : '\n  "aria-label"?: string;'}
}

export interface RadioGroupProps {
  /** Group label read by screen readers */
  legend: string;
  /** Currently selected value */
  value?: string;
  /** Default selected value (uncontrolled) */
  defaultValue?: string;
  /** Callback when selection changes */
  onChange?: (value: string) => void;
  /** Layout direction */
  orientation?: "horizontal" | "vertical";
  /** Disabled state applied to all radios */
  disabled?: boolean;
  children: React.ReactNode;
}

// ─── Size map ─────────────────────────────────────────────────────────────────

const SIZE_BOX: Record<"sm" | "md" | "lg", string> = {
  sm: "14px",
  md: "16px",
  lg: "20px",
};

const SIZE_FONT: Record<"sm" | "md" | "lg", string> = {
  sm: "var(--font-size-caption, 0.75rem)",
  md: "var(--font-size-small, 0.875rem)",
  lg: "var(--font-size-body, 1rem)",
};

// ─── Context ──────────────────────────────────────────────────────────────────

interface RadioGroupContext {
  value: string | undefined;
  onChange: (value: string) => void;
  disabled: boolean;
  name: string;
}

const RadioContext = React.createContext<RadioGroupContext | null>(null);

// ─── RadioGroup ───────────────────────────────────────────────────────────────

export function RadioGroup({
  legend,
  value: controlledValue,
  defaultValue,
  onChange,
  orientation = "vertical",
  disabled = false,
  children,
}: RadioGroupProps) {
  const name = React.useId();
  const [internalValue, setInternalValue] = React.useState(defaultValue);
  const isControlled = controlledValue !== undefined;
  const resolvedValue = isControlled ? controlledValue : internalValue;

  const handleChange = (val: string) => {
    if (!isControlled) setInternalValue(val);
    onChange?.(val);
  };

  return (
    <RadioContext.Provider
      value={{ value: resolvedValue, onChange: handleChange, disabled, name }}
    >
      <fieldset
        style={{
          border: "none",
          padding: 0,
          margin: 0,
          display: "flex",
          flexDirection: orientation === "horizontal" ? "row" : "column",
          gap: orientation === "horizontal"
            ? "var(--spacing-4, 16px)"
            : "var(--spacing-2, 8px)",
          fontFamily: "var(--font-family-base, inherit)",
        }}
      >
        <legend
          style={{
            fontSize: "var(--font-size-small, 0.875rem)",
            fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
            color: "var(--color-text-primary, #111827)",
            marginBottom: "var(--spacing-2, 8px)",
            padding: 0,
            float: "left",
            width: "100%",
          }}
        >
          {legend}
        </legend>
        {children}
      </fieldset>
    </RadioContext.Provider>
  );
}

RadioGroup.displayName = "RadioGroup";

// ─── Radio ────────────────────────────────────────────────────────────────────

export const Radio = React.forwardRef<HTMLInputElement, RadioProps>(
  function Radio(
    {
      label,
      size = "md",
      disabled: propDisabled,
      value,
      style,
      id: propId,
      onChange,
      ...props
    },
    ref,
  ) {
    const id = propId ?? React.useId();
    const ctx = React.useContext(RadioContext);
    const [isFocusVisible, setIsFocusVisible] = React.useState(false);

    const isDisabled = propDisabled ?? ctx?.disabled ?? false;
    const isChecked = ctx ? ctx.value === value : props.checked;
    const name = ctx?.name ?? props.name;
    const boxSize = SIZE_BOX[size];

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      if (e.target.checked) {
        ctx?.onChange(e.target.value);
      }
      onChange?.(e);
    };

    const ringStyle: React.CSSProperties = isFocusVisible
      ? {
          boxShadow: [
            "0 0 0 var(--focus-ring-offset, 2px) var(--color-bg-default, #fff)",
            "0 0 0 calc(var(--focus-ring-offset, 2px) + var(--focus-ring-width, 2px)) var(--focus-ring-color, #2563eb)",
          ].join(", "),
        }
      : {};

    return (
      <label
        htmlFor={id}
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "var(--spacing-2, 8px)",
          cursor: isDisabled ? "not-allowed" : "pointer",
          opacity: isDisabled ? "var(--state-disabled-opacity, 0.4)" : 1,
          fontFamily: "var(--font-family-base, inherit)",
          ...style,
        }}
      >
        {/* Hidden native input */}
        <input
          ref={ref}
          type="radio"
          id={id}
          name={name}
          value={value}
          checked={isChecked}
          disabled={isDisabled}
          onChange={handleChange}
          onKeyUp={() => setIsFocusVisible(true)}
          onMouseDown={() => setIsFocusVisible(false)}
          onBlur={() => setIsFocusVisible(false)}
          style={{
            position: "absolute",
            opacity: 0,
            width: boxSize,
            height: boxSize,
            margin: 0,
            cursor: isDisabled ? "not-allowed" : "pointer",
          }}
          {...props}
        />

        {/* Custom visual circle */}
        <span
          aria-hidden="true"
          style={{
            width: boxSize,
            height: boxSize,
            flexShrink: 0,
            borderRadius: "50%",
            border: \`2px solid \${
              isChecked
                ? "var(--radio-color, var(--color-action, #2563eb))"
                : "var(--radio-border, var(--color-border-default, #e2e8f0))"
            }\`,
            background: "var(--radio-bg, var(--color-bg-default, #ffffff))",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            transition: \`border-color var(--duration-fast, 100ms)\`,
            pointerEvents: "none",
            ...ringStyle,
          }}
        >
          {isChecked && (
            <span
              style={{
                width: \`calc(\${boxSize} / 2)\`,
                height: \`calc(\${boxSize} / 2)\`,
                borderRadius: "50%",
                background: "var(--radio-color, var(--color-action, #2563eb))",
              }}
            />
          )}
        </span>

        {label && (
          <span
            style={{
              fontSize: SIZE_FONT[size],
              color: "var(--color-text-primary, #111827)",
              lineHeight: "var(--line-height-body, 1.5)",
            }}
          >
            {label}
          </span>
        )}
      </label>
    );
  },
);

Radio.displayName = "Radio";
`;
}
