/**
 * Select component generator.
 * Generates a typed, accessible React Select wrapping the native <select> element.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateSelect(
  config: DesignSystemConfig,
  _rule: ComponentRule | undefined,
): string {
  return `/**
 * Select — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface SelectProps
  extends Omit<React.SelectHTMLAttributes<HTMLSelectElement>, "size"> {
  /** Visible label */
  label?: string;
  /** Helper text shown below */
  helperText?: string;
  /** Error message — also applies error styling when present */
  errorMessage?: string;
  /** Size preset */
  size?: "sm" | "md" | "lg";
  /** Placeholder option (value = "") */
  placeholder?: string;
  /** Structured option list — alternatively use <option> children */
  options?: SelectOption[];
  /** Full-width */
  fullWidth?: boolean;
  "aria-label"?: string;
}

// ─── Size styles ──────────────────────────────────────────────────────────────

const SIZE_PADDING: Record<"sm" | "md" | "lg", string> = {
  sm: "var(--spacing-1, 4px) var(--spacing-2, 8px)",
  md: "var(--component-padding-sm, 8px) var(--component-padding-md, 16px)",
  lg: "var(--component-padding-md, 16px) var(--component-padding-lg, 24px)",
};

const SIZE_FONT: Record<"sm" | "md" | "lg", string> = {
  sm: "var(--font-size-caption, 0.75rem)",
  md: "var(--font-size-small, 0.875rem)",
  lg: "var(--font-size-body, 1rem)",
};

// ─── Chevron icon ─────────────────────────────────────────────────────────────

function ChevronDown({ size = 16 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      style={{ flexShrink: 0, pointerEvents: "none" }}
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

// ─── Component ────────────────────────────────────────────────────────────────

export const Select = React.forwardRef<HTMLSelectElement, SelectProps>(
  function Select(
    {
      label,
      helperText,
      errorMessage,
      size = "md",
      placeholder,
      options,
      fullWidth = false,
      disabled,
      style,
      id: propId,
      children,
      ...props
    },
    ref,
  ) {
    const id = propId ?? React.useId();
    const errorId = \`\${id}-error\`;
    const helperId = \`\${id}-helper\`;
    const hasError = Boolean(errorMessage);
    const [isFocused, setIsFocused] = React.useState(false);

    const borderColor = hasError
      ? "var(--color-danger-border, #fca5a5)"
      : isFocused
        ? "var(--input-border-focus, var(--color-border-focus, #2563eb))"
        : "var(--select-border, var(--color-border-default, #e2e8f0))";

    const focusShadow = isFocused
      ? [
          "0 0 0 var(--focus-ring-offset, 2px) var(--color-bg-default, #fff)",
          "0 0 0 calc(var(--focus-ring-offset, 2px) + var(--focus-ring-width, 2px)) var(--focus-ring-color, #2563eb)",
        ].join(", ")
      : undefined;

    const wrapperStyle: React.CSSProperties = {
      display: "flex",
      flexDirection: "column",
      gap: "var(--spacing-1, 4px)",
      fontFamily: "var(--font-family-base, inherit)",
      width: fullWidth ? "100%" : undefined,
      opacity: disabled ? "var(--state-disabled-opacity, 0.4)" : 1,
    };

    const selectWrapperStyle: React.CSSProperties = {
      position: "relative",
      display: "flex",
      alignItems: "center",
      background: "var(--select-bg, var(--color-bg-default, #ffffff))",
      border: \`1px solid \${borderColor}\`,
      borderRadius: "var(--select-radius, var(--radius-md, 4px))",
      boxShadow: focusShadow,
      transition: "border-color var(--duration-fast, 100ms), box-shadow var(--duration-fast, 100ms)",
      cursor: disabled ? "not-allowed" : "pointer",
    };

    const selectStyle: React.CSSProperties = {
      flex: 1,
      appearance: "none",
      WebkitAppearance: "none",
      background: "var(--select-bg, var(--color-bg-default, #ffffff))",
      border: "none",
      outline: "none",
      padding: SIZE_PADDING[size],
      paddingRight: "var(--spacing-8, 32px)",
      fontSize: SIZE_FONT[size],
      color: "var(--color-text-primary, #111827)",
      lineHeight: "var(--line-height-body, 1.5)",
      cursor: disabled ? "not-allowed" : "pointer",
      width: "100%",
      ...style,
    };

    return (
      <div style={wrapperStyle}>
        {label && (
          <label
            htmlFor={id}
            style={{
              fontSize: "var(--font-size-label, 0.875rem)",
              fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
              color: "var(--color-text-primary, #111827)",
              lineHeight: "var(--line-height-label, 1.4)",
            }}
          >
            {label}
          </label>
        )}

        <div style={selectWrapperStyle}>
          <select
            ref={ref}
            id={id}
            disabled={disabled}
            aria-invalid={hasError ? "true" : undefined}
            aria-describedby={
              [hasError ? errorId : null, helperText ? helperId : null]
                .filter(Boolean)
                .join(" ") || undefined
            }
            style={selectStyle}
            onFocus={() => setIsFocused(true)}
            onBlur={() => setIsFocused(false)}
            {...props}
          >
            {placeholder && (
              <option value="" disabled>
                {placeholder}
              </option>
            )}
            {options
              ? options.map((opt) => (
                  <option key={opt.value} value={opt.value} disabled={opt.disabled}>
                    {opt.label}
                  </option>
                ))
              : children}
          </select>

          <span
            aria-hidden="true"
            style={{
              position: "absolute",
              right: "var(--spacing-2, 8px)",
              display: "flex",
              alignItems: "center",
              color: "var(--color-text-secondary, #6b7280)",
              pointerEvents: "none",
            }}
          >
            <ChevronDown size={size === "sm" ? 14 : 16} />
          </span>
        </div>

        {hasError && (
          <span
            id={errorId}
            role="alert"
            style={{
              fontSize: "var(--font-size-caption, 0.75rem)",
              color: "var(--color-danger-fg, #dc2626)",
            }}
          >
            {errorMessage}
          </span>
        )}

        {helperText && !hasError && (
          <span
            id={helperId}
            style={{
              fontSize: "var(--font-size-caption, 0.75rem)",
              color: "var(--color-text-secondary, #6b7280)",
            }}
          >
            {helperText}
          </span>
        )}
      </div>
    );
  },
);

Select.displayName = "Select";
`;
}
