/**
 * Spinner component generator.
 * Generates a typed, accessible React Spinner for loading states.
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateSpinner(
  config: DesignSystemConfig,
  _rule: ComponentRule | undefined,
): string {
  return `/**
 * Spinner — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type SpinnerSize = "xs" | "sm" | "md" | "lg" | "xl";
export type SpinnerVariant = "default" | "primary" | "inverted";

export interface SpinnerProps extends React.SVGProps<SVGSVGElement> {
  /** Size preset */
  size?: SpinnerSize;
  /** Color variant */
  variant?: SpinnerVariant;
  /** Accessible label for screen readers */
  label?: string;
}

// ─── Size map ─────────────────────────────────────────────────────────────────

const SIZE_PX: Record<SpinnerSize, number> = {
  xs: 12,
  sm: 16,
  md: 24,
  lg: 32,
  xl: 48,
};

const STROKE_WIDTH: Record<SpinnerSize, number> = {
  xs: 2.5,
  sm: 2.5,
  md: 2,
  lg: 2,
  xl: 1.5,
};

// ─── Variant color ────────────────────────────────────────────────────────────

const VARIANT_COLOR: Record<SpinnerVariant, string> = {
  default: "var(--spinner-color, var(--color-text-secondary, #6b7280))",
  primary: "var(--spinner-color-primary, var(--color-action, #2563eb))",
  inverted: "var(--spinner-color-inverted, #ffffff)",
};

// ─── Keyframe injection ───────────────────────────────────────────────────────

if (typeof document !== "undefined") {
  const styleId = "dsforge-spinner-keyframes";
  if (!document.getElementById(styleId)) {
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = \`
      @keyframes dsforge-spin {
        to { transform: rotate(360deg); }
      }
    \`;
    document.head.appendChild(style);
  }
}

// ─── Component ────────────────────────────────────────────────────────────────

export function Spinner({
  size = "md",
  variant = "default",
  label = "Loading…",
  style,
  ...props
}: SpinnerProps) {
  const px = SIZE_PX[size];
  const sw = STROKE_WIDTH[size];
  const color = VARIANT_COLOR[variant];
  const r = (px / 2) - sw;
  const circumference = 2 * Math.PI * r;
  const dashOffset = circumference * 0.25;

  return (
    <span
      role="status"
      aria-label={label}
      style={{ display: "inline-flex", flexShrink: 0 }}
    >
      <svg
        width={px}
        height={px}
        viewBox={\`0 0 \${px} \${px}\`}
        fill="none"
        aria-hidden="true"
        style={{
          animation: "dsforge-spin 0.75s linear infinite",
          color,
          ...style,
        }}
        {...props}
      >
        {/* Track */}
        <circle
          cx={px / 2}
          cy={px / 2}
          r={r}
          stroke="currentColor"
          strokeWidth={sw}
          opacity={0.2}
        />
        {/* Arc */}
        <circle
          cx={px / 2}
          cy={px / 2}
          r={r}
          stroke="currentColor"
          strokeWidth={sw}
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={dashOffset}
          transform={\`rotate(-90 \${px / 2} \${px / 2})\`}
        />
      </svg>
      <span
        style={{
          position: "absolute",
          width: 1,
          height: 1,
          padding: 0,
          margin: -1,
          overflow: "hidden",
          clip: "rect(0,0,0,0)",
          whiteSpace: "nowrap",
          borderWidth: 0,
        }}
      >
        {label}
      </span>
    </span>
  );
}

Spinner.displayName = "Spinner";
`;
}
