/**
 * Toast/Alert component generator.
 * Generates typed, accessible React Toast and Alert components.
 * - Alert: inline, static, always visible
 * - Toast: overlay notification with auto-dismiss and ToastProvider
 */

import type { DesignSystemConfig, ComponentRule } from "../../../types/index";

export function generateToast(
  config: DesignSystemConfig,
  rule: ComponentRule | undefined,
): string {
  const variants = rule?.allowedVariants ?? [
    "default",
    "success",
    "warning",
    "danger",
    "info",
  ];
  const variantType = variants.map((v) => `"${v}"`).join(" | ");

  return `/**
 * Toast / Alert — ${config.meta.name}
 *
 * Generated by dsforge. Extend via design-system.rules.json or component token overrides.
 * Exports: Alert, Toast, ToastProvider, useToast
 * Allowed variants: ${variants.join(", ")}
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type ToastVariant = ${variantType};

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Visual/semantic variant */
  variant?: ToastVariant;
  /** Alert title */
  title?: string;
  /** Dismissible — shows a close button */
  dismissible?: boolean;
  /** Called when dismissed */
  onDismiss?: () => void;
  children?: React.ReactNode;
}

export interface ToastItem {
  id: string;
  variant?: ToastVariant;
  title?: string;
  message: string;
  duration?: number;
}

export interface ToastContextValue {
  add: (toast: Omit<ToastItem, "id">) => void;
  remove: (id: string) => void;
}

// ─── Variant tokens ───────────────────────────────────────────────────────────

const VARIANT_STYLES: Record<ToastVariant, { bg: string; border: string; icon: string; text: string }> = {
  default: {
    bg: "var(--alert-bg-default, var(--color-bg-subtle, #f8fafc))",
    border: "var(--alert-border-default, var(--color-border-default, #e2e8f0))",
    icon: "var(--color-text-secondary, #6b7280)",
    text: "var(--color-text-primary, #111827)",
  },
  success: {
    bg: "var(--alert-bg-success, var(--color-success-subtle, #dcfce7))",
    border: "var(--alert-border-success, var(--color-success-border, #86efac))",
    icon: "var(--color-success-fg, #16a34a)",
    text: "var(--color-success-fg, #16a34a)",
  },
  warning: {
    bg: "var(--alert-bg-warning, var(--color-warning-subtle, #fef9c3))",
    border: "var(--alert-border-warning, var(--color-warning-border, #fde047))",
    icon: "var(--color-warning-fg, #ca8a04)",
    text: "var(--color-warning-fg, #ca8a04)",
  },
  danger: {
    bg: "var(--alert-bg-danger, var(--color-danger-subtle, #fee2e2))",
    border: "var(--alert-border-danger, var(--color-danger-border, #fca5a5))",
    icon: "var(--color-danger-fg, #dc2626)",
    text: "var(--color-danger-fg, #dc2626)",
  },
  info: {
    bg: "var(--alert-bg-info, var(--color-info-subtle, #dbeafe))",
    border: "var(--alert-border-info, var(--color-info-border, #93c5fd))",
    icon: "var(--color-info-fg, #2563eb)",
    text: "var(--color-info-fg, #2563eb)",
  },
};

// ─── Icon ─────────────────────────────────────────────────────────────────────

function AlertIcon({ variant, size = 18 }: { variant: ToastVariant; size?: number }) {
  const color = VARIANT_STYLES[variant].icon;
  const shared = {
    width: size,
    height: size,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: color,
    strokeWidth: 2,
    strokeLinecap: "round" as const,
    strokeLinejoin: "round" as const,
    "aria-hidden": true as const,
    style: { flexShrink: 0 },
  };

  if (variant === "success") {
    return <svg {...shared}><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>;
  }
  if (variant === "danger") {
    return <svg {...shared}><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>;
  }
  if (variant === "warning") {
    return <svg {...shared}><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>;
  }
  if (variant === "info") {
    return <svg {...shared}><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>;
  }
  return <svg {...shared}><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>;
}

function CloseButton({ onClick, color }: { onClick: () => void; color: string }) {
  return (
    <button
      type="button"
      onClick={onClick}
      aria-label="Dismiss"
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "transparent",
        border: "none",
        cursor: "pointer",
        color,
        padding: "var(--spacing-1, 4px)",
        borderRadius: "var(--radius-sm, 2px)",
        flexShrink: 0,
        opacity: 0.7,
      }}
    >
      <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" aria-hidden>
        <line x1="18" y1="6" x2="6" y2="18"/>
        <line x1="6" y1="6" x2="18" y2="18"/>
      </svg>
    </button>
  );
}

// ─── Alert (inline, static) ───────────────────────────────────────────────────

export function Alert({
  variant = "default",
  title,
  dismissible = false,
  onDismiss,
  children,
  style,
  ...props
}: AlertProps) {
  const [visible, setVisible] = React.useState(true);
  const tokens = VARIANT_STYLES[variant];

  const handleDismiss = () => {
    setVisible(false);
    onDismiss?.();
  };

  if (!visible) return null;

  return (
    <div
      role="alert"
      style={{
        display: "flex",
        gap: "var(--spacing-3, 12px)",
        padding: "var(--component-padding-sm, 12px) var(--component-padding-md, 16px)",
        borderRadius: "var(--alert-radius, var(--radius-md, 4px))",
        border: \`1px solid \${tokens.border}\`,
        background: tokens.bg,
        fontFamily: "var(--font-family-base, inherit)",
        ...style,
      }}
      {...props}
    >
      <AlertIcon variant={variant} />

      <div style={{ flex: 1, minWidth: 0 }}>
        {title && (
          <p
            style={{
              margin: 0,
              fontSize: "var(--font-size-small, 0.875rem)",
              fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
              color: tokens.text,
              lineHeight: "var(--line-height-label, 1.4)",
            }}
          >
            {title}
          </p>
        )}
        {children && (
          <div
            style={{
              marginTop: title ? "var(--spacing-1, 4px)" : 0,
              fontSize: "var(--font-size-small, 0.875rem)",
              color: "var(--color-text-secondary, #6b7280)",
              lineHeight: "var(--line-height-body, 1.5)",
            }}
          >
            {children}
          </div>
        )}
      </div>

      {dismissible && (
        <CloseButton onClick={handleDismiss} color={tokens.text} />
      )}
    </div>
  );
}

Alert.displayName = "Alert";

// ─── Toast context ────────────────────────────────────────────────────────────

const ToastContext = React.createContext<ToastContextValue | null>(null);

// ─── ToastProvider ────────────────────────────────────────────────────────────

export function ToastProvider({ children }: { children: React.ReactNode }) {
  const [toasts, setToasts] = React.useState<ToastItem[]>([]);

  const add = React.useCallback((toast: Omit<ToastItem, "id">) => {
    const id = Math.random().toString(36).slice(2);
    setToasts((prev) => [...prev, { id, ...toast }]);
  }, []);

  const remove = React.useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  return (
    <ToastContext.Provider value={{ add, remove }}>
      {children}
      <div
        aria-live="polite"
        aria-atomic="false"
        style={{
          position: "fixed",
          bottom: "var(--spacing-6, 24px)",
          right: "var(--spacing-6, 24px)",
          display: "flex",
          flexDirection: "column",
          gap: "var(--spacing-2, 8px)",
          zIndex: 9999,
          maxWidth: "360px",
          width: "calc(100vw - var(--spacing-12, 48px))",
          pointerEvents: "none",
        }}
      >
        {toasts.map((toast) => (
          <Toast key={toast.id} {...toast} onClose={() => remove(toast.id)} />
        ))}
      </div>
    </ToastContext.Provider>
  );
}

ToastProvider.displayName = "ToastProvider";

// ─── useToast hook ────────────────────────────────────────────────────────────

export function useToast(): ToastContextValue {
  const ctx = React.useContext(ToastContext);
  if (!ctx) {
    throw new Error("useToast must be used within a <ToastProvider>.");
  }
  return ctx;
}

// ─── Toast (overlay) ──────────────────────────────────────────────────────────

interface ToastInternalProps extends ToastItem {
  onClose: () => void;
}

function Toast({ variant = "default", title, message, duration = 5000, onClose }: ToastInternalProps) {
  const tokens = VARIANT_STYLES[variant];

  React.useEffect(() => {
    if (duration <= 0) return;
    const timer = setTimeout(onClose, duration);
    return () => clearTimeout(timer);
  }, [duration, onClose]);

  return (
    <div
      role="status"
      style={{
        display: "flex",
        gap: "var(--spacing-3, 12px)",
        padding: "var(--component-padding-sm, 12px) var(--component-padding-md, 16px)",
        borderRadius: "var(--toast-radius, var(--radius-md, 4px))",
        background: "var(--toast-bg, var(--color-bg-default, #ffffff))",
        border: \`1px solid \${tokens.border}\`,
        boxShadow: "var(--elevation-3, 0 4px 12px rgba(0,0,0,0.15))",
        fontFamily: "var(--font-family-base, inherit)",
        pointerEvents: "all",
        animation: "dsforge-toast-in 200ms var(--easing-standard, ease) forwards",
      }}
    >
      <AlertIcon variant={variant} />

      <div style={{ flex: 1, minWidth: 0 }}>
        {title && (
          <p
            style={{
              margin: 0,
              fontSize: "var(--font-size-small, 0.875rem)",
              fontWeight: "var(--font-weight-label, 500)" as React.CSSProperties["fontWeight"],
              color: "var(--color-text-primary, #111827)",
              lineHeight: "var(--line-height-label, 1.4)",
            }}
          >
            {title}
          </p>
        )}
        <p
          style={{
            margin: 0,
            marginTop: title ? "var(--spacing-1, 4px)" : 0,
            fontSize: "var(--font-size-small, 0.875rem)",
            color: "var(--color-text-secondary, #6b7280)",
            lineHeight: "var(--line-height-body, 1.5)",
          }}
        >
          {message}
        </p>
      </div>

      <CloseButton onClick={onClose} color={tokens.text} />
    </div>
  );
}

// ─── Keyframe injection ───────────────────────────────────────────────────────

if (typeof document !== "undefined") {
  const styleId = "dsforge-toast-keyframes";
  if (!document.getElementById(styleId)) {
    const style = document.createElement("style");
    style.id = styleId;
    style.textContent = \`
      @keyframes dsforge-toast-in {
        from { opacity: 0; transform: translateY(8px) scale(0.97); }
        to   { opacity: 1; transform: translateY(0) scale(1); }
      }
    \`;
    document.head.appendChild(style);
  }
}
`;
}
