/**
 * CSS custom property emitter.
 *
 * Generates one .css file per theme, plus a base.css with all resolved tokens.
 * Consumers import the appropriate theme file to activate that theme's tokens.
 *
 * Output format:
 *   :root[data-theme="light"] { --color-action: #2563eb; ... }
 */

import type { DesignSystemConfig } from "../../types/index";
import type { ResolutionResult } from "../../core/token-resolver";
import {
  PRESETS,
  SPACING_PRESETS,
  RADIUS_PRESETS,
  CONTROL_SIZE_PRESETS,
  buildSemanticSpacing,
} from "../../presets/index";

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Convert a token name to a CSS custom property name */
function cssVar(name: string): string {
  return `--${name}`;
}

/** Emit a block of CSS custom property declarations */
function emitBlock(
  selector: string,
  entries: Array<[string, string]>,
  comment?: string,
): string {
  if (entries.length === 0) return "";
  const lines: string[] = [];
  if (comment) lines.push(`/* ${comment} */`);
  lines.push(`${selector} {`);
  for (const [name, value] of entries) {
    lines.push(`  ${cssVar(name)}: ${value};`);
  }
  lines.push("}");
  return lines.join("\n");
}

// ─── Base CSS ─────────────────────────────────────────────────────────────────

/**
 * Emit base.css — all resolved semantic + component tokens as :root vars.
 * This file is always safe to import regardless of theme.
 */
export function emitBaseCss(
  config: DesignSystemConfig,
  resolution: ResolutionResult,
): string {
  const sections: string[] = [];
  const header = [
    `/* ─── ${config.meta.name} — base tokens ────────────────────────────── */`,
    `/* Generated by dsforge. Do not edit manually.                            */`,
    `/* Import this file, then add a theme file for light/dark mode.         */`,
    "",
  ].join("\n");

  // ── Semantic tokens ──
  const semanticEntries: Array<[string, string]> = Object.entries(
    resolution.tokens,
  )
    .filter(([k]) => k.startsWith("semantic."))
    .map(([k, v]) => [k.replace("semantic.", ""), v]);

  if (semanticEntries.length > 0) {
    sections.push(emitBlock(":root", semanticEntries, "Semantic tokens"));
  }

  // ── Component tokens ──
  const componentEntries: Array<[string, string]> = Object.entries(
    resolution.tokens,
  )
    .filter(([k]) => k.startsWith("component."))
    .map(([k, v]) => [k.replace("component.", ""), v]);

  if (componentEntries.length > 0) {
    sections.push(emitBlock(":root", componentEntries, "Component tokens"));
  }

  // ── Spacing ──
  const spacing = config.spacing;
  const spacingEntries: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(spacing?.scale ?? {})) {
    spacingEntries.push([`spacing-${key}`, `${value}px`]);
  }
  for (const [key, value] of Object.entries(spacing?.semantic ?? {})) {
    spacingEntries.push([key, `${value}px`]);
  }
  if (spacingEntries.length > 0) {
    sections.push(emitBlock(":root", spacingEntries, "Spacing"));
  }

  // ── Typography ──
  const typo = config.typography;
  const typoEntries: Array<[string, string]> = [];
  if (typo?.fontFamily) {
    typoEntries.push(["font-family-base", typo.fontFamily]);
  }
  for (const [role, value] of Object.entries(typo?.roles ?? {})) {
    if (!value) continue;
    typoEntries.push([`font-size-${role}`, `${value.size}px`]);
    typoEntries.push([`font-weight-${role}`, String(value.weight)]);
    typoEntries.push([`line-height-${role}`, String(value.lineHeight)]);
    if (value.letterSpacing !== undefined && value.letterSpacing !== 0) {
      typoEntries.push([`letter-spacing-${role}`, String(value.letterSpacing)]);
    }
  }
  if (typoEntries.length > 0) {
    sections.push(emitBlock(":root", typoEntries, "Typography"));
  }

  // ── Control sizes ──
  const currentPreset = (config.philosophy?.density ?? "comfortable") as import("../../presets/index").Preset;
  const controlSizes = CONTROL_SIZE_PRESETS[currentPreset] ?? CONTROL_SIZE_PRESETS.comfortable;
  sections.push(
    emitBlock(
      ":root",
      [
        ["control-size-sm", `${controlSizes.sm}px`],
        ["control-size-md", `${controlSizes.md}px`],
        ["control-size-lg", `${controlSizes.lg}px`],
      ],
      "Control sizes",
    ),
  );

  // ── Radius ──
  const radiusEntries: Array<[string, string]> = Object.entries(
    config.radius ?? {},
  )
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => [`radius-${k}`, v === 9999 ? "9999px" : `${v}px`]);
  if (radiusEntries.length > 0) {
    sections.push(emitBlock(":root", radiusEntries, "Border radius"));
  }

  // ── Elevation ──
  const elevEntries: Array<[string, string]> = Object.entries(
    config.elevation ?? {},
  ).map(([k, v]) => [`shadow-${k}`, v]);
  if (elevEntries.length > 0) {
    sections.push(emitBlock(":root", elevEntries, "Elevation / shadows"));
  }

  // ── Motion ──
  const motionEntries: Array<[string, string]> = [];
  for (const [key, ms] of Object.entries(config.motion?.duration ?? {})) {
    if (ms !== undefined) motionEntries.push([`duration-${key}`, `${ms}ms`]);
  }
  for (const [key, curve] of Object.entries(config.motion?.easing ?? {})) {
    if (curve !== undefined) motionEntries.push([`easing-${key}`, curve]);
  }
  if (motionEntries.length > 0) {
    sections.push(emitBlock(":root", motionEntries, "Motion"));
  }

  // ── States ──
  const states = config.states;
  const stateEntries: Array<[string, string]> = [];
  if (states?.hoverOpacity !== undefined)
    stateEntries.push(["state-hover-opacity", String(states.hoverOpacity)]);
  if (states?.activeOpacity !== undefined)
    stateEntries.push(["state-active-opacity", String(states.activeOpacity)]);
  if (states?.disabledOpacity !== undefined)
    stateEntries.push([
      "state-disabled-opacity",
      String(states.disabledOpacity),
    ]);
  if (states?.focusRing) {
    const fr = states.focusRing;
    // Resolve focus ring color if it's a token reference
    const frColor =
      resolution.tokens[String(fr.color).replace(/[{}]/g, "")] ??
      String(fr.color);
    stateEntries.push(["focus-ring-color", frColor]);
    stateEntries.push(["focus-ring-width", fr.width]);
    stateEntries.push(["focus-ring-offset", fr.offset]);
  }
  if (stateEntries.length > 0) {
    sections.push(emitBlock(":root", stateEntries, "Interactive states"));
  }

  return [header, ...sections].join("\n\n") + "\n";
}

// ─── Theme CSS ────────────────────────────────────────────────────────────────

/**
 * Emit a theme-specific CSS file.
 * The generated selector is :root[data-theme="themeName"].
 */
export function emitThemeCss(
  themeName: string,
  themeOverrides: Record<string, string | number>,
  config: DesignSystemConfig,
): string {
  const lines: string[] = [
    `/* ─── ${config.meta.name} — ${themeName} theme ───────────────────────── */`,
    `/* Generated by dsforge. Do not edit manually.                            */`,
    `/* Usage: <html data-theme="${themeName}"> or ThemeProvider theme="${themeName}"  */`,
    "",
  ];

  const entries: Array<[string, string]> = Object.entries(themeOverrides).map(
    ([k, v]) => [k, String(v)],
  );

  lines.push(emitBlock(`:root[data-theme="${themeName}"]`, entries));
  return lines.join("\n") + "\n";
}

// ─── Density CSS (Pro) ────────────────────────────────────────────────────────

/**
 * Emit density.css — all three density presets as [data-density] attribute
 * selectors. Importing this file enables runtime density switching without
 * regenerating: set data-density on the root element or use DensityProvider.
 *
 * Pro feature. Not emitted for free-tier builds.
 */
export function emitDensityCss(config: DesignSystemConfig): string {
  const lines: string[] = [
    `/* ─── ${config.meta.name} — density presets ──────────────────────────── */`,
    `/* Generated by dsforge. Do not edit manually.                            */`,
    `/* Pro feature: import this file to enable runtime density switching.     */`,
    `/* Usage: <html data-density="compact | comfortable | spacious">          */`,
    `/*   or wrap with <DensityProvider density="compact">                     */`,
    "",
  ];

  for (const preset of PRESETS) {
    const scale = SPACING_PRESETS[preset];
    const radius = RADIUS_PRESETS[preset];
    const semantic = buildSemanticSpacing(scale);

    const entries: Array<[string, string]> = [];

    // Spacing scale
    for (const [key, value] of Object.entries(scale)) {
      entries.push([`spacing-${key}`, `${value}px`]);
    }

    // Semantic spacing
    for (const [key, value] of Object.entries(semantic)) {
      entries.push([key, `${value}px`]);
    }

    // Radius
    for (const [key, value] of Object.entries(radius)) {
      entries.push([`radius-${key}`, value === 9999 ? "9999px" : `${value}px`]);
    }

    // Control sizes (checkbox, radio)
    const controlSizes = CONTROL_SIZE_PRESETS[preset];
    entries.push(["control-size-sm", `${controlSizes.sm}px`]);
    entries.push(["control-size-md", `${controlSizes.md}px`]);
    entries.push(["control-size-lg", `${controlSizes.lg}px`]);

    lines.push(emitBlock(`[data-density="${preset}"]`, entries, `Preset: ${preset}`));
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Entry point ──────────────────────────────────────────────────────────────

export interface CssFile {
  filename: string;
  content: string;
}

/**
 * Generate all CSS files from a resolved config.
 * Returns an array of { filename, content } pairs ready to write to disk.
 */
export function generateCssFiles(
  config: DesignSystemConfig,
  resolution: ResolutionResult,
): CssFile[] {
  const files: CssFile[] = [];

  // base.css — all structural tokens (spacing, typography, radius, etc.)
  files.push({
    filename: "base.css",
    content: emitBaseCss(config, resolution),
  });

  // One theme file per defined theme
  for (const [themeName, themeOverrides] of Object.entries(
    config.themes ?? {},
  )) {
    files.push({
      filename: `${themeName}.css`,
      content: emitThemeCss(themeName, themeOverrides, config),
    });
  }

  // If no themes were defined at all, emit a minimal fallback
  if (!config.themes || Object.keys(config.themes).length === 0) {
    const fallbackEntries: Array<[string, string]> = Object.entries(
      resolution.tokens,
    )
      .filter(([k]) => k.startsWith("semantic."))
      .map(([k, v]) => [k.replace("semantic.", ""), v]);

    files.push({
      filename: "light.css",
      content: [
        `/* ${config.meta.name} — default theme (no themes defined in config) */`,
        emitBlock(":root", fallbackEntries),
        "",
      ].join("\n"),
    });
  }

  return files;
}
