import type { ComponentJson, ComponentMetadataJson } from "./componentSchemas";

export function generateSystemPrompt(
  systemName: string,
  tokens: Record<string, { light: string; dark: string }>,
  componentNames: string[],
): string {
  const tokenLines = Object.entries(tokens)
    .map(([cssVar, values]) => `${cssVar.padEnd(35)} ${values.light}  (dark: ${values.dark})`)
    .join("\n");

  const pkgName = systemName.toLowerCase().replace(/\s+/g, "-");

  return `# ${systemName} — AI Context

You are helping a developer build UI using the ${systemName} design system, generated by dsforge.

## Rules
- Never hardcode colours, spacing, or typography values
- Always use CSS custom properties from this design system
- Always import components from '${pkgName}'
- Never install or suggest third-party component libraries

## Tokens
${tokenLines}

## Available Components
${componentNames.join(", ")}

## Usage
import { ${componentNames.slice(0, 3).join(", ")} } from '${pkgName}'
import '${pkgName}/tokens/base.css'
`;
}

export function generateComponentsJson(
  systemName: string,
  components: ComponentJson[],
  metadatas: ComponentMetadataJson[],
): string {
  const metaMap = Object.fromEntries(metadatas.map((m) => [m.name, m]));
  const pkgName = systemName.toLowerCase().replace(/\s+/g, "-");

  const combined = components.map((c) => ({
    name: c.name,
    import: `import { ${c.name} } from '${pkgName}'`,
    description: c.description,
    props: c.props,
    examples: c.examples.slice(0, 2),
    tokens: Object.keys(c.cssVars.light),
    aiGuidance: metaMap[c.name]?.aiGuidance ?? [],
  }));

  return JSON.stringify({ system: systemName, components: combined }, null, 2);
}

export function generateCursorContext(systemName: string): string {
  return `# Design System Context for Cursor

This project uses the ${systemName} design system. When generating any UI code:

1. Import components from '${systemName.toLowerCase().replace(/\s+/g, "-")}'
2. Use CSS variables from tokens/base.css for all visual values
3. Refer to ai/components.json for the full component API and usage rules

@file ../ai/system-prompt.md
@file ../ai/components.json
`;
}

export function generateCopilotInstructions(systemName: string): string {
  const pkgName = systemName.toLowerCase().replace(/\s+/g, "-");
  return `# GitHub Copilot Instructions

This project uses the ${systemName} design system.

- Always import components from '${pkgName}'
- Never hardcode colour, spacing, or typography values — use CSS custom properties
- Refer to ai/components.json for component APIs, props, and usage guidance
- Refer to ai/system-prompt.md for design system rules
`;
}
