import type { ComponentJson } from "./componentSchemas";

interface RegistryItem {
  name: string;
  type: "registry:ui";
  description: string;
  files: Array<{ path: string; type: "registry:component" }>;
  cssVars: { light: Record<string, string>; dark: Record<string, string> };
}

interface Registry {
  $schema: string;
  name: string;
  version: string;
  description: string;
  items: RegistryItem[];
}

export function generateRegistry(
  systemName: string,
  version: string,
  components: ComponentJson[],
): Registry {
  return {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: systemName,
    version,
    description: `Design system generated by dsforge`,
    items: components.map((c) => ({
      name: c.name.toLowerCase(),
      type: "registry:ui",
      description: c.description,
      files: [{ path: `components/${c.name}/${c.name}.tsx`, type: "registry:component" }],
      cssVars: c.cssVars,
    })),
  };
}
