import { DesignSystemConfig, GovernanceRules } from "../types";
import { resolveTokens } from "../utils/resolve-tokens";
import * as path from "path";
import * as fs from "fs-extra";
import prettier from "prettier";

export async function generateComponents(
  config: DesignSystemConfig,
  rules: GovernanceRules,
  outputDir: string,
): Promise<void> {
  const componentsDir = path.join(outputDir, "components");
  await fs.ensureDir(componentsDir);

  const t = resolveTokens(config);
  const allowedVariants = rules.button?.allowedVariants ?? [
    "primary",
    "secondary",
    "danger",
  ];

  await writeComponent(
    componentsDir,
    "Button",
    generateButton(t, allowedVariants),
  );
  await writeComponent(componentsDir, "Input", generateInput(t));
  await writeComponent(componentsDir, "Card", generateCard(t, rules));
  await writeComponent(
    componentsDir,
    "Typography",
    generateTypography(t, config.typography.scale),
  );
  await writeComponent(componentsDir, "Stack", generateStack(t));

  const barrel = await prettier.format(
    `// Auto-generated by dsforge — do not edit manually
export { Button }     from './Button';
export type { ButtonProps }     from './Button';
export { Input }      from './Input';
export type { InputProps }      from './Input';
export { Card }       from './Card';
export type { CardProps }       from './Card';
export { Typography } from './Typography';
export type { TypographyProps } from './Typography';
export { Stack }      from './Stack';
export type { StackProps }      from './Stack';
`,
    { parser: "typescript" },
  );
  await fs.writeFile(path.join(componentsDir, "index.ts"), barrel);
}

async function writeComponent(
  dir: string,
  name: string,
  code: string,
): Promise<void> {
  const formatted = await prettier.format(code, { parser: "typescript" });
  await fs.writeFile(path.join(dir, `${name}.tsx`), formatted);
}

// ─── Button ───────────────────────────────────────────────────────────────────

function generateButton(
  t: ReturnType<typeof resolveTokens>,
  allowedVariants: string[],
): string {
  const variantStyles = allowedVariants
    .map((v) => {
      const bg =
        v === "primary"
          ? t.colorPrimary
          : v === "danger"
            ? t.colorDanger
            : t.colorSecondary;
      return `  ${v}: { backgroundColor: '${bg}', color: '${t.colorOnPrimary}', border: '${t.borderWidth} solid transparent' }`;
    })
    .join(",\n");

  return `import React from 'react';

export type ButtonVariant = ${allowedVariants.map((v) => `'${v}'`).join(" | ")};

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  children: React.ReactNode;
  /** Required for icon-only buttons */
  'aria-label'?: string;
}

const variantStyles: Record<ButtonVariant, React.CSSProperties> = {
${variantStyles}
};

const baseStyle: React.CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: '${t.spaceSm} ${t.spaceLg}',
  borderRadius: '${t.radiusMd}',
  fontSize: '${t.fontSizeMd}',
  fontWeight: ${t.fontWeightMedium},
  fontFamily: '${t.fontFamily}, sans-serif',
  lineHeight: ${t.lineHeightTight},
  cursor: 'pointer',
  transition: '${t.transition}',
  outline: 'none',
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  children,
  style,
  ...props
}) => (
  <button
    {...props}
    style={{ ...baseStyle, ...variantStyles[variant], ...style }}
    onFocus={(e) => {
      e.currentTarget.style.boxShadow = '${t.focusRing}';
      props.onFocus?.(e);
    }}
    onBlur={(e) => {
      e.currentTarget.style.boxShadow = 'none';
      props.onBlur?.(e);
    }}
  >
    {children}
  </button>
);
`;
}

// ─── Input ────────────────────────────────────────────────────────────────────

function generateInput(t: ReturnType<typeof resolveTokens>): string {
  return `import React from 'react';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label: string;
  error?: string;
  hint?: string;
}

const inputBase: React.CSSProperties = {
  display: 'block',
  width: '100%',
  padding: '${t.spaceSm} ${t.spaceMd}',
  borderRadius: '${t.radiusMd}',
  border: '${t.borderWidth} solid ${t.colorSecondary}',
  fontSize: '${t.fontSizeMd}',
  fontFamily: '${t.fontFamily}, sans-serif',
  lineHeight: ${t.lineHeightNormal},
  color: '${t.colorText}',
  backgroundColor: '${t.colorBackground}',
  boxSizing: 'border-box',
  outline: 'none',
  transition: 'border-color ${t.duration} ${t.easing}, box-shadow ${t.duration} ${t.easing}',
};

export const Input: React.FC<InputProps> = ({
  label,
  error,
  hint,
  id,
  style,
  ...props
}) => {
  const inputId = id ?? label.toLowerCase().replace(/\\s+/g, '-');
  const hintId  = hint  ? \`\${inputId}-hint\`  : undefined;
  const errorId = error ? \`\${inputId}-error\` : undefined;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '${t.spaceXs}' }}>
      <label
        htmlFor={inputId}
        style={{
          fontSize: '${t.fontSizeMd}',
          fontWeight: ${t.fontWeightMedium},
          fontFamily: '${t.fontFamily}, sans-serif',
          lineHeight: ${t.lineHeightSnug},
          color: '${t.colorText}',
        }}
      >
        {label}
      </label>
      <input
        {...props}
        id={inputId}
        aria-describedby={[hintId, errorId].filter(Boolean).join(' ') || undefined}
        aria-invalid={!!error}
        style={{
          ...inputBase,
          borderColor: error ? '${t.colorDanger}' : '${t.colorSecondary}',
          ...style,
        }}
        onFocus={(e) => {
          e.currentTarget.style.boxShadow = '${t.focusRing}';
          props.onFocus?.(e);
        }}
        onBlur={(e) => {
          e.currentTarget.style.boxShadow = 'none';
          props.onBlur?.(e);
        }}
      />
      {hint && !error && (
        <span id={hintId} style={{ fontSize: '${t.fontSizeSm}', lineHeight: ${t.lineHeightLoose}, color: '${t.colorSecondary}', fontFamily: '${t.fontFamily}, sans-serif' }}>
          {hint}
        </span>
      )}
      {error && (
        <span id={errorId} role="alert" style={{ fontSize: '${t.fontSizeSm}', lineHeight: ${t.lineHeightLoose}, color: '${t.colorDanger}', fontFamily: '${t.fontFamily}, sans-serif' }}>
          {error}
        </span>
      )}
    </div>
  );
};
`;
}

// ─── Card ─────────────────────────────────────────────────────────────────────

function generateCard(
  t: ReturnType<typeof resolveTokens>,
  rules: GovernanceRules,
): string {
  const maxWidth = rules.card?.maxWidth ?? "600px";

  return `import React from 'react';

export type CardShadow = 'none' | 'small' | 'medium';

export interface CardProps {
  children:  React.ReactNode;
  shadow?:   CardShadow;
  style?:    React.CSSProperties;
  as?:       React.ElementType;
}

const shadowMap: Record<CardShadow, string> = {
  none:   '${t.shadowNone}',
  small:  '${t.shadowSmall}',
  medium: '${t.shadowMedium}',
};

export const Card: React.FC<CardProps> = ({
  children,
  shadow = 'small',
  style,
  as: Tag = 'div',
}) => (
  <Tag
    style={{
      backgroundColor: '${t.colorBackground}',
      borderRadius:    '${t.radiusLg}',
      padding:         '${t.spaceXl}',
      maxWidth:        '${maxWidth}',
      boxShadow:       shadowMap[shadow],
      border:          '${t.borderWidth} solid ${t.colorBorder}',
      ...style,
    }}
  >
    {children}
  </Tag>
);
`;
}

// ─── Typography ───────────────────────────────────────────────────────────────

function generateTypography(
  t: ReturnType<typeof resolveTokens>,
  scale: number[],
): string {
  const s = (i: number, fallback: number) => `${scale[i] ?? fallback}px`;

  return `import React from 'react';

export type TypographyVariant = 'h1' | 'h2' | 'h3' | 'h4' | 'body' | 'small' | 'caption';

export interface TypographyProps {
  variant?: TypographyVariant;
  children: React.ReactNode;
  color?:   string;
  style?:   React.CSSProperties;
  as?:      React.ElementType;
}

const variantStyles: Record<TypographyVariant, React.CSSProperties> = {
  h1:      { fontSize: '${s(5, 32)}', fontWeight: ${t.fontWeightSemibold}, lineHeight: ${t.lineHeightTight}  },
  h2:      { fontSize: '${s(4, 24)}', fontWeight: ${t.fontWeightSemibold}, lineHeight: ${t.lineHeightTight}  },
  h3:      { fontSize: '${s(3, 20)}', fontWeight: ${t.fontWeightMedium},   lineHeight: ${t.lineHeightSnug}   },
  h4:      { fontSize: '${s(2, 16)}', fontWeight: ${t.fontWeightMedium},   lineHeight: ${t.lineHeightSnug}   },
  body:    { fontSize: '${s(2, 16)}', fontWeight: ${t.fontWeightRegular},  lineHeight: ${t.lineHeightNormal} },
  small:   { fontSize: '${s(1, 14)}', fontWeight: ${t.fontWeightRegular},  lineHeight: ${t.lineHeightLoose}  },
  caption: { fontSize: '${s(0, 12)}', fontWeight: ${t.fontWeightRegular},  lineHeight: ${t.lineHeightLoose}  },
};

const defaultTagMap: Record<TypographyVariant, React.ElementType> = {
  h1: 'h1', h2: 'h2', h3: 'h3', h4: 'h4',
  body: 'p', small: 'p', caption: 'span',
};

export const Typography: React.FC<TypographyProps> = ({
  variant = 'body',
  children,
  color = '${t.colorText}',
  style,
  as,
}) => {
  const Tag = as ?? defaultTagMap[variant];
  return (
    <Tag
      style={{
        fontFamily: '${t.fontFamily}, sans-serif',
        color,
        margin: 0,
        ...variantStyles[variant],
        ...style,
      }}
    >
      {children}
    </Tag>
  );
};
`;
}

// ─── Stack ────────────────────────────────────────────────────────────────────

function generateStack(t: ReturnType<typeof resolveTokens>): string {
  return `import React from 'react';

export interface StackProps {
  children:   React.ReactNode;
  direction?: 'row' | 'column';
  /** Spacing multiplier — 1 unit = ${t.spaceXs} */
  gap?:       number;
  align?:     React.CSSProperties['alignItems'];
  justify?:   React.CSSProperties['justifyContent'];
  wrap?:      boolean;
  style?:     React.CSSProperties;
  as?:        React.ElementType;
}

/** Base spacing unit in px (respects density: ${t.spaceXs} = 1×) */
const SPACE_UNIT = ${t.spaceUnit};

export const Stack: React.FC<StackProps> = ({
  children,
  direction = 'column',
  gap       = 2,
  align     = 'stretch',
  justify   = 'flex-start',
  wrap      = false,
  style,
  as: Tag   = 'div',
}) => (
  <Tag
    style={{
      display:        'flex',
      flexDirection:  direction,
      gap:            \`\${gap * SPACE_UNIT}px\`,
      alignItems:     align,
      justifyContent: justify,
      flexWrap:       wrap ? 'wrap' : 'nowrap',
      ...style,
    }}
  >
    {children}
  </Tag>
);
`;
}
