import { DesignSystemConfig, GovernanceRules } from "../types";
import * as path from "path";
import * as fs from "fs-extra";
import prettier from "prettier";

export async function generateComponents(
  config: DesignSystemConfig,
  rules: GovernanceRules,
  outputDir: string,
): Promise<void> {
  const componentsDir = path.join(outputDir, "components");
  await fs.ensureDir(componentsDir);

  const allowedVariants = rules.button?.allowedVariants ?? [
    "primary",
    "secondary",
    "danger",
  ];

  await writeComponent(
    componentsDir,
    "Button",
    generateButton(config, allowedVariants),
  );
  await writeComponent(componentsDir, "Input", generateInput(config));
  await writeComponent(componentsDir, "Card", generateCard(config, rules));
  await writeComponent(componentsDir, "Typography", generateTypography(config));
  await writeComponent(componentsDir, "Stack", generateStack(config));

  // Barrel export
  const indexContent = await prettier.format(
    `// Auto-generated by dsgen — do not edit manually
export { Button } from './Button';
export type { ButtonProps } from './Button';
export { Input } from './Input';
export type { InputProps } from './Input';
export { Card } from './Card';
export type { CardProps } from './Card';
export { Typography } from './Typography';
export type { TypographyProps } from './Typography';
export { Stack } from './Stack';
export type { StackProps } from './Stack';
`,
    { parser: "typescript" },
  );
  await fs.writeFile(path.join(componentsDir, "index.ts"), indexContent);
}

async function writeComponent(
  dir: string,
  name: string,
  code: string,
): Promise<void> {
  const formatted = await prettier.format(code, { parser: "typescript" });
  await fs.writeFile(path.join(dir, `${name}.tsx`), formatted);
}

function generateButton(
  config: DesignSystemConfig,
  allowedVariants: string[],
): string {
  const { color, spacing, radius } = config;
  const pad = `${spacing.baseUnit * 2}px ${spacing.baseUnit * 4}px`;
  const br = `${radius.scale[1]}px`;

  const variantStyles = allowedVariants
    .map((v) => {
      const bg =
        v === "primary"
          ? color.primary
          : v === "danger"
            ? color.danger
            : color.secondary;
      return `${v}: {
      backgroundColor: '${bg}',
      color: '${color.background}',
      border: 'none',
    }`;
    })
    .join(",\n");

  return `import React from 'react';

export type ButtonVariant = ${allowedVariants.map((v) => `'${v}'`).join(" | ")};

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  children: React.ReactNode;
  /** aria-label is required for icon-only buttons */
  'aria-label'?: string;
}

const variantStyles: Record<ButtonVariant, React.CSSProperties> = {
  ${variantStyles}
};

const baseStyle: React.CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: '${pad}',
  borderRadius: '${br}',
  fontSize: '14px',
  fontWeight: 500,
  cursor: 'pointer',
  transition: 'opacity 0.15s ease',
  maxWidth: '${config.spacing.baseUnit * 75}px',
  outline: 'none',
};

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  children,
  style,
  ...props
}) => {
  return (
    <button
      {...props}
      style={{ ...baseStyle, ...variantStyles[variant], ...style }}
      onFocus={(e) => {
        e.currentTarget.style.boxShadow = '0 0 0 3px rgba(37,99,235,0.4)';
        props.onFocus?.(e);
      }}
      onBlur={(e) => {
        e.currentTarget.style.boxShadow = 'none';
        props.onBlur?.(e);
      }}
    >
      {children}
    </button>
  );
};
`;
}

function generateInput(config: DesignSystemConfig): string {
  const { color, spacing, radius } = config;
  const pad = `${spacing.baseUnit * 2}px ${spacing.baseUnit * 3}px`;
  const br = `${radius.scale[1]}px`;

  return `import React from 'react';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label: string;
  error?: string;
  hint?: string;
}

const inputStyle: React.CSSProperties = {
  display: 'block',
  width: '100%',
  padding: '${pad}',
  borderRadius: '${br}',
  border: '1px solid ${color.secondary}',
  fontSize: '14px',
  color: '${color.text}',
  backgroundColor: '${color.background}',
  boxSizing: 'border-box',
  outline: 'none',
};

export const Input: React.FC<InputProps> = ({
  label,
  error,
  hint,
  id,
  style,
  ...props
}) => {
  const inputId = id ?? label.toLowerCase().replace(/\\s+/g, '-');
  const hintId = hint ? \`\${inputId}-hint\` : undefined;
  const errorId = error ? \`\${inputId}-error\` : undefined;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '${spacing.baseUnit}px' }}>
      <label
        htmlFor={inputId}
        style={{ fontSize: '14px', fontWeight: 500, color: '${color.text}' }}
      >
        {label}
      </label>
      <input
        {...props}
        id={inputId}
        aria-describedby={[hintId, errorId].filter(Boolean).join(' ') || undefined}
        aria-invalid={!!error}
        style={{
          ...inputStyle,
          borderColor: error ? '${color.danger}' : '${color.secondary}',
          ...style,
        }}
        onFocus={(e) => {
          e.currentTarget.style.boxShadow = '0 0 0 3px rgba(37,99,235,0.3)';
          props.onFocus?.(e);
        }}
        onBlur={(e) => {
          e.currentTarget.style.boxShadow = 'none';
          props.onBlur?.(e);
        }}
      />
      {hint && !error && (
        <span id={hintId} style={{ fontSize: '12px', color: '${color.secondary}' }}>{hint}</span>
      )}
      {error && (
        <span id={errorId} role="alert" style={{ fontSize: '12px', color: '${color.danger}' }}>{error}</span>
      )}
    </div>
  );
};
`;
}

function generateCard(
  config: DesignSystemConfig,
  rules: GovernanceRules,
): string {
  const { color, spacing, radius } = config;
  const maxWidth = rules.card?.maxWidth ?? "600px";
  const pad = `${spacing.baseUnit * 6}px`;
  const br = `${radius.scale[2]}px`;

  return `import React from 'react';

export type CardShadow = 'none' | 'small' | 'medium';

export interface CardProps {
  children: React.ReactNode;
  shadow?: CardShadow;
  style?: React.CSSProperties;
  as?: React.ElementType;
}

const shadowMap: Record<CardShadow, string> = {
  none: 'none',
  small: '0 1px 3px rgba(0,0,0,0.1)',
  medium: '0 4px 12px rgba(0,0,0,0.12)',
};

export const Card: React.FC<CardProps> = ({
  children,
  shadow = 'small',
  style,
  as: Tag = 'div',
}) => {
  return (
    <Tag
      style={{
        backgroundColor: '${color.background}',
        borderRadius: '${br}',
        padding: '${pad}',
        maxWidth: '${maxWidth}',
        boxShadow: shadowMap[shadow],
        border: '1px solid rgba(0,0,0,0.06)',
        ...style,
      }}
    >
      {children}
    </Tag>
  );
};
`;
}

function generateTypography(config: DesignSystemConfig): string {
  const { color, typography } = config;
  const scale = typography.scale;

  return `import React from 'react';

export type TypographyVariant = 'h1' | 'h2' | 'h3' | 'h4' | 'body' | 'small' | 'caption';

export interface TypographyProps {
  variant?: TypographyVariant;
  children: React.ReactNode;
  color?: string;
  style?: React.CSSProperties;
  as?: React.ElementType;
}

const variantMap: Record<TypographyVariant, React.CSSProperties> = {
  h1: { fontSize: '${scale[5]}px', fontWeight: 600, lineHeight: 1.2 },
  h2: { fontSize: '${scale[4]}px', fontWeight: 600, lineHeight: 1.3 },
  h3: { fontSize: '${scale[3]}px', fontWeight: 500, lineHeight: 1.4 },
  h4: { fontSize: '${scale[2]}px', fontWeight: 500, lineHeight: 1.4 },
  body: { fontSize: '${scale[2]}px', fontWeight: 400, lineHeight: 1.6 },
  small: { fontSize: '${scale[1]}px', fontWeight: 400, lineHeight: 1.5 },
  caption: { fontSize: '${scale[0]}px', fontWeight: 400, lineHeight: 1.4 },
};

const defaultTagMap: Record<TypographyVariant, React.ElementType> = {
  h1: 'h1', h2: 'h2', h3: 'h3', h4: 'h4',
  body: 'p', small: 'p', caption: 'span',
};

export const Typography: React.FC<TypographyProps> = ({
  variant = 'body',
  children,
  color = '${color.text}',
  style,
  as,
}) => {
  const Tag = as ?? defaultTagMap[variant];
  return (
    <Tag
      style={{
        fontFamily: '${typography.fontFamily}, sans-serif',
        color,
        margin: 0,
        ...variantMap[variant],
        ...style,
      }}
    >
      {children}
    </Tag>
  );
};
`;
}

function generateStack(config: DesignSystemConfig): string {
  const { spacing } = config;

  return `import React from 'react';

export interface StackProps {
  children: React.ReactNode;
  direction?: 'row' | 'column';
  gap?: number;
  align?: React.CSSProperties['alignItems'];
  justify?: React.CSSProperties['justifyContent'];
  wrap?: boolean;
  style?: React.CSSProperties;
  as?: React.ElementType;
}

export const Stack: React.FC<StackProps> = ({
  children,
  direction = 'column',
  gap = 2,
  align = 'stretch',
  justify = 'flex-start',
  wrap = false,
  style,
  as: Tag = 'div',
}) => {
  return (
    <Tag
      style={{
        display: 'flex',
        flexDirection: direction,
        gap: \`\${gap * ${spacing.baseUnit}}px\`,
        alignItems: align,
        justifyContent: justify,
        flexWrap: wrap ? 'wrap' : 'nowrap',
        ...style,
      }}
    >
      {children}
    </Tag>
  );
};
`;
}
