import { ComponentMetadata } from "../types";
import * as path from "path";
import * as fs from "fs-extra";

export async function generateDocs(
  metadata: ComponentMetadata[],
  outputDir: string,
): Promise<void> {
  const docsDir = path.join(outputDir, "docs");
  await fs.ensureDir(docsDir);

  for (const meta of metadata) {
    const mdx = buildMDX(meta);
    await fs.writeFile(path.join(docsDir, `${meta.component}.mdx`), mdx);
  }

  // Index doc
  const index = buildIndexDoc(metadata);
  await fs.writeFile(path.join(docsDir, "index.mdx"), index);
}

function buildMDX(meta: ComponentMetadata): string {
  const variantsSection = meta.variants?.length
    ? `## Variants\n\n${meta.variants.map((v) => `- \`${v}\``).join("\n")}\n`
    : "";

  const tokensTable = Object.entries(meta.tokens)
    .map(([k, v]) => `| \`${k}\` | \`${v}\` |`)
    .join("\n");

  const accessibilityList = [
    meta.accessibilityContract.keyboard && "✅ Keyboard navigable",
    meta.accessibilityContract.focusRing !== "none" &&
      `✅ Focus ring: ${meta.accessibilityContract.focusRing}`,
    meta.accessibilityContract.ariaLabel &&
      `📋 aria-label: ${meta.accessibilityContract.ariaLabel}`,
  ]
    .filter(Boolean)
    .join("\n");

  return `---
title: ${meta.component}
description: Auto-generated documentation for ${meta.component}
---

# ${meta.component}

> Auto-generated by dsforge — do not edit manually

## Overview

| Property | Value |
|----------|-------|
| Role | \`${meta.role}\` |
| Hierarchy Level | \`${meta.hierarchyLevel}\` |
| Interaction Model | \`${meta.interactionModel}\` |
| Layout Impact | \`${meta.layoutImpact}\` |
| Destructive | ${meta.destructive ? "⚠️ Yes" : "No"} |

${variantsSection}
## Design Tokens

| Token | Value |
|-------|-------|
${tokensTable}

## Accessibility

${accessibilityList}

## Usage

\`\`\`tsx
import { ${meta.component} } from './components';

// Basic usage
<${meta.component}${meta.variants ? ` variant="${meta.variants[0]}"` : ""}>
  Content here
</${meta.component}>
\`\`\`

## AI Metadata

This component's AI-consumable metadata is available at \`metadata/${meta.component}.json\`.
It describes the component's role, interaction model, and accessibility contract for AI agents.
`;
}

function buildIndexDoc(components: ComponentMetadata[]): string {
  const componentList = components
    .map((c) => `- [${c.component}](./${c.component}.mdx) — ${c.role}`)
    .join("\n");

  return `---
title: Design System
description: Auto-generated design system documentation
---

# Design System

> Auto-generated by dsforge — do not edit manually

## Components

${componentList}

## Getting Started

\`\`\`tsx
import { Button, Input, Card, Typography, Stack } from './components';
\`\`\`

## Governance

Components are validated against \`design-system.rules.json\`. Run \`dsforge validate\` to check for violations.
`;
}
