import { DesignSystemConfig } from "../types";
import * as path from "path";
import * as fs from "fs-extra";
import prettier from "prettier";

export async function generateTokens(
  config: DesignSystemConfig,
  outputDir: string,
): Promise<void> {
  const tokensDir = path.join(outputDir, "tokens");
  await fs.ensureDir(tokensDir);

  const tokens = buildTokenObject(config);

  // Write TypeScript tokens
  const tsContent = await prettier.format(
    `// Auto-generated by dsgen — do not edit manually
export const tokens = ${JSON.stringify(tokens, null, 2)} as const;
export type Tokens = typeof tokens;
`,
    { parser: "typescript" },
  );

  await fs.writeFile(path.join(tokensDir, "index.ts"), tsContent);

  // Write CSS custom properties
  const cssVars = buildCSSVars(tokens);
  const cssContent = `/* Auto-generated by dsgen — do not edit manually */
:root {
${cssVars}
}
`;
  await fs.writeFile(path.join(tokensDir, "tokens.css"), cssContent);
}

function buildTokenObject(config: DesignSystemConfig): Record<string, unknown> {
  const { baseUnit } = config.spacing;

  return {
    color: config.color,
    typography: {
      fontFamily: config.typography.fontFamily,
      scale: Object.fromEntries(
        config.typography.scale.map((size, i) => [`size${i + 1}`, `${size}px`]),
      ),
      fontWeights: Object.fromEntries(
        config.typography.fontWeights.map((w) => [
          w === 400
            ? "regular"
            : w === 500
              ? "medium"
              : w === 600
                ? "semibold"
                : w === 700
                  ? "bold"
                  : `w${w}`,
          w,
        ]),
      ),
    },
    spacing: Object.fromEntries(
      [1, 2, 3, 4, 5, 6, 8, 10, 12, 16].map((multiplier) => [
        `space${multiplier}`,
        `${multiplier * baseUnit}px`,
      ]),
    ),
    radius: Object.fromEntries(
      config.radius.scale.map((r, i) => [`radius${i + 1}`, `${r}px`]),
    ),
  };
}

function buildCSSVars(tokens: Record<string, unknown>, prefix = ""): string {
  const lines: string[] = [];

  for (const [key, value] of Object.entries(tokens)) {
    const varName = prefix ? `${prefix}-${key}` : `--${key}`;
    if (typeof value === "object" && value !== null) {
      lines.push(buildCSSVars(value as Record<string, unknown>, varName));
    } else {
      lines.push(`  ${varName}: ${value};`);
    }
  }

  return lines.join("\n");
}
