/**
 * JS + TypeScript token emitter.
 *
 * Generates:
 *   tokens.js   — CommonJS-compatible object literal (also valid ESM)
 *   tokens.d.ts — TypeScript type declarations
 *
 * Consumers can import individual tokens by name for use in
 * CSS-in-JS, React Native, or anywhere that needs raw values at runtime.
 */

import type { DesignSystemConfig } from "../../../types/index";
import type { ResolutionResult } from "../../../core/token-resolver";

// Quote JS object keys that would be invalid unquoted (start with digit, contain hyphen etc.)
function safeKey(k: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Convert a token path ("semantic.color-action") to a JS identifier ("colorAction").
 * Strips the layer prefix and camelCases the remainder.
 */
function toJsIdentifier(tokenPath: string): string {
  // Remove layer prefix
  const withoutLayer = tokenPath.replace(/^(global|semantic|component)\./, "");
  // camelCase: split on - and capitalize each word after the first
  return withoutLayer
    .split("-")
    .map((part, i) =>
      i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");
}

/** Wrap a value in quotes if it contains spaces or special chars, else leave plain */
function formatValue(value: string): string {
  // Always use quoted strings for token values in JS
  return JSON.stringify(value);
}

// ─── tokens.js emitter ───────────────────────────────────────────────────────

/**
 * Emit tokens.js — a flat ESM export of all resolved tokens.
 */
export function emitJsTokens(
  config: DesignSystemConfig,
  resolution: ResolutionResult,
): string {
  const lines: string[] = [
    `// ${config.meta.name} — design tokens`,
    `// Generated by dsforge v${config.meta.version}. Do not edit manually.`,
    "",
    "// ─── Resolved token map ─────────────────────────────────────────────────",
    "export const tokens = {",
  ];

  // Group by layer for readability
  const layers = ["global", "semantic", "component"] as const;
  for (const layer of layers) {
    const entries = Object.entries(resolution.tokens).filter(([k]) =>
      k.startsWith(`${layer}.`),
    );
    if (entries.length === 0) continue;

    lines.push(`  // ${layer}`);
    for (const [tokenPath, value] of entries) {
      const identifier = toJsIdentifier(tokenPath);
      lines.push(`  ${identifier}: ${formatValue(value)},`);
    }
  }

  lines.push("} as const;", "");
  lines.push("export type TokenKey = keyof typeof tokens;", "");

  // ── Theme maps ──
  const themes = config.themes ?? {};
  if (Object.keys(themes).length > 0) {
    lines.push(
      "// ─── Theme overrides ────────────────────────────────────────────────────",
    );
    lines.push("export const themes = {");
    for (const [themeName, overrides] of Object.entries(themes)) {
      lines.push(`  "${themeName}": {`);
      for (const [k, v] of Object.entries(overrides)) {
        lines.push(`    ${JSON.stringify(k)}: ${JSON.stringify(String(v))},`);
      }
      lines.push("  },");
    }
    lines.push("} as const;", "");
    lines.push("export type ThemeName = keyof typeof themes;", "");
  }

  // ── Spacing scale ──
  const spacingScale = config.spacing?.scale ?? {};
  if (Object.keys(spacingScale).length > 0) {
    lines.push(
      "// ─── Spacing scale ──────────────────────────────────────────────────────",
    );
    lines.push("export const spacing = {");
    for (const [key, value] of Object.entries(spacingScale)) {
      lines.push(`  ${JSON.stringify(key)}: ${value},  // ${value}px`);
    }
    lines.push("} as const;", "");
  }

  // ── Typography roles ──
  const typoRoles = config.typography?.roles ?? {};
  if (Object.keys(typoRoles).length > 0) {
    lines.push(
      "// ─── Typography roles ───────────────────────────────────────────────────",
    );
    lines.push("export const typography = {");
    for (const [role, value] of Object.entries(typoRoles)) {
      if (!value) continue;
      lines.push(`  ${role}: {`);
      lines.push(`    size: ${value.size},`);
      lines.push(`    weight: ${value.weight},`);
      lines.push(`    lineHeight: ${value.lineHeight},`);
      if (value.letterSpacing !== undefined) {
        lines.push(
          `    letterSpacing: ${JSON.stringify(String(value.letterSpacing))},`,
        );
      }
      if (value.fontFamily) {
        lines.push(`    fontFamily: ${JSON.stringify(value.fontFamily)},`);
      }
      lines.push("  },");
    }
    lines.push("} as const;", "");
  }

  // ── Radius ──
  const radius = config.radius ?? {};
  if (Object.keys(radius).length > 0) {
    lines.push(
      "// ─── Border radius ──────────────────────────────────────────────────────",
    );
    lines.push("export const radius = {");
    for (const [key, value] of Object.entries(radius)) {
      if (value === undefined) continue;
      const cssValue = value === 9999 ? "9999px" : `${value}px`;
      lines.push(`  ${key}: ${JSON.stringify(cssValue)},`);
    }
    lines.push("} as const;", "");
  }

  // ── Elevation ──
  const elevation = config.elevation ?? {};
  if (Object.keys(elevation).length > 0) {
    lines.push(
      "// ─── Elevation / shadows ────────────────────────────────────────────────",
    );
    lines.push("export const elevation = {");
    for (const [key, value] of Object.entries(elevation)) {
      lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
    }
    lines.push("} as const;", "");
  }

  return lines.join("\n");
}

// ─── Tailwind config emitter ──────────────────────────────────────────────────

/**
 * Emit tailwind.config.js — a Tailwind CSS theme extension.
 * Consumers spread this into their tailwind.config.js `theme.extend`.
 */
export function emitTailwindConfig(config: DesignSystemConfig): string {
  const lines: string[] = [
    `// ${config.meta.name} — Tailwind CSS theme extension`,
    `// Generated by dsforge. Do not edit manually.`,
    `//`,
    `// Usage in tailwind.config.js:`,
    `//   const ds = require('./${config.meta.name}/tokens/tailwind');`,
    `//   module.exports = { theme: { extend: ds } };`,
    "",
    "module.exports = {",
  ];

  // ── colors ──
  const interactive = config.color?.interactive?.primary;
  const surface = config.color?.surface;
  const border = config.color?.border;
  const text = config.color?.text;
  const status = config.color?.status ?? {};

  lines.push("  colors: {");

  if (interactive) {
    lines.push("    action: {");
    if (interactive.rest) lines.push(`      DEFAULT: 'var(--color-action)',`);
    if (interactive.hover)
      lines.push(`      hover: 'var(--color-action-hover)',`);
    if (interactive.active)
      lines.push(`      active: 'var(--color-action-active)',`);
    if (interactive.disabled)
      lines.push(`      disabled: 'var(--color-action-disabled)',`);
    lines.push("    },");
  }

  if (surface) {
    lines.push("    surface: {");
    if (surface.default)
      lines.push(`      DEFAULT: 'var(--color-bg-default)',`);
    if (surface.subtle) lines.push(`      subtle: 'var(--color-bg-subtle)',`);
    if (surface.overlay)
      lines.push(`      overlay: 'var(--color-bg-overlay)',`);
    if (surface.inverse)
      lines.push(`      inverse: 'var(--color-bg-inverse)',`);
    lines.push("    },");
  }

  if (border) {
    lines.push("    border: {");
    if (border.default)
      lines.push(`      DEFAULT: 'var(--color-border-default)',`);
    if (border.strong)
      lines.push(`      strong: 'var(--color-border-strong)',`);
    if (border.focus) lines.push(`      focus: 'var(--color-border-focus)',`);
    lines.push("    },");
  }

  if (text) {
    lines.push("    text: {");
    if (text.primary) lines.push(`      DEFAULT: 'var(--color-text-primary)',`);
    if (text.secondary)
      lines.push(`      secondary: 'var(--color-text-secondary)',`);
    if (text.disabled)
      lines.push(`      disabled: 'var(--color-text-disabled)',`);
    if (text.inverse) lines.push(`      inverse: 'var(--color-text-inverse)',`);
    lines.push("    },");
  }

  for (const [statusName, statusValue] of Object.entries(status)) {
    if (!statusValue) continue;
    lines.push(`    ${safeKey(statusName)}: {`);
    lines.push(`      bg: 'var(--color-${statusName}-bg)',`);
    lines.push(`      DEFAULT: 'var(--color-${statusName}-fg)',`);
    lines.push(`      border: 'var(--color-${statusName}-border)',`);
    lines.push("    },");
  }

  lines.push("  },");

  // ── spacing ──
  const spacingScale = config.spacing?.scale ?? {};
  if (Object.keys(spacingScale).length > 0) {
    lines.push("  spacing: {");
    for (const [key, value] of Object.entries(spacingScale)) {
      lines.push(`    ${JSON.stringify(key)}: '${value}px',`);
    }
    lines.push("  },");
  }

  // ── fontSize (typography roles) ──
  const roles = config.typography?.roles ?? {};
  if (Object.keys(roles).length > 0) {
    lines.push("  fontSize: {");
    for (const [role, value] of Object.entries(roles)) {
      if (!value) continue;
      const ls = value.letterSpacing
        ? `, letterSpacing: '${value.letterSpacing}'`
        : "";
      lines.push(
        `    ${safeKey(role)}: ['${value.size}px', { lineHeight: '${value.lineHeight}'${ls} }],`,
      );
    }
    lines.push("  },");
  }

  // ── fontWeight ──
  const weights = new Set<number>();
  for (const role of Object.values(config.typography?.roles ?? {})) {
    if (role) weights.add(role.weight);
  }
  if (weights.size > 0) {
    lines.push("  fontWeight: {");
    const weightNames: Record<number, string> = {
      100: "thin",
      200: "extralight",
      300: "light",
      400: "normal",
      500: "medium",
      600: "semibold",
      700: "bold",
      800: "extrabold",
      900: "black",
    };
    for (const w of [...weights].sort()) {
      const name = weightNames[w] ?? String(w);
      lines.push(`    ${safeKey(name)}: '${w}',`);
    }
    lines.push("  },");
  }

  // ── borderRadius ──
  const radiusConfig = config.radius ?? {};
  if (Object.keys(radiusConfig).length > 0) {
    lines.push("  borderRadius: {");
    for (const [key, value] of Object.entries(radiusConfig)) {
      if (value === undefined) continue;
      const cssValue = value === 9999 ? "9999px" : `${value}px`;
      const twKey =
        key === "none" ? "none" : key === "full" ? "full" : `ds-${key}`;
      lines.push(`    ${safeKey(twKey)}: '${cssValue}',`);
    }
    lines.push("  },");
  }

  // ── boxShadow ──
  const elevationConfig = config.elevation ?? {};
  if (Object.keys(elevationConfig).length > 0) {
    lines.push("  boxShadow: {");
    for (const [key, value] of Object.entries(elevationConfig)) {
      lines.push(
        `    ${JSON.stringify(`ds-${key}`)}: ${JSON.stringify(value)},`,
      );
    }
    lines.push("  },");
  }

  // ── screens (breakpoints) ──
  const breakpoints = config.layout?.breakpoints ?? {};
  if (Object.keys(breakpoints).length > 0) {
    lines.push("  screens: {");
    for (const [key, value] of Object.entries(breakpoints)) {
      if (value !== undefined) lines.push(`    ${safeKey(key)}: '${value}px',`);
    }
    lines.push("  },");
  }

  // ── transitionDuration ──
  const durations = config.motion?.duration ?? {};
  if (Object.keys(durations).length > 0) {
    lines.push("  transitionDuration: {");
    for (const [key, value] of Object.entries(durations)) {
      if (value !== undefined) lines.push(`    ${safeKey(key)}: '${value}ms',`);
    }
    lines.push("  },");
  }

  // ── transitionTimingFunction ──
  const easing = config.motion?.easing ?? {};
  if (Object.keys(easing).length > 0) {
    lines.push("  transitionTimingFunction: {");
    for (const [key, value] of Object.entries(easing)) {
      if (value !== undefined)
        lines.push(`    ${safeKey(key)}: ${JSON.stringify(value)},`);
    }
    lines.push("  },");
  }

  lines.push("};", "");
  return lines.join("\n");
}
