/**
 * Package emitter.
 *
 * Generates the package.json and README.md for the published npm package.
 * The published package is what consumers install — it's separate from the
 * dsforge tool itself.
 */

import type { DesignSystemConfig } from "../../types/index";

// ─── package.json ─────────────────────────────────────────────────────────────

export function generatePackageJson(
  config: DesignSystemConfig,
  componentNames: string[],
): string {
  const scope = config.meta.npmScope ?? "@myorg";
  const name = `${scope}/${config.meta.name}`;

  const pkg = {
    name,
    version: config.meta.version,
    description: config.meta.description ?? `${config.meta.name} design system`,
    keywords: ["design-system", "tokens", "react", "typescript", "components"],
    license: "MIT",
    type: "module",
    main: "./dist/index.js",
    types: "./dist/index.d.ts",
    exports: {
      ".": {
        import: "./dist/index.js",
        types: "./dist/index.d.ts",
      },
      "./tokens/base.css": "./tokens/base.css",
      ...Object.fromEntries(
        Object.keys({} as Record<string, unknown>)
          .concat(["light", "dark"])
          .map((t) => [`./tokens/${t}.css`, `./tokens/${t}.css`]),
      ),
      "./tokens": "./tokens/tokens.js",
      "./tailwind": "./tokens/tailwind.js",
      ...Object.fromEntries(
        componentNames.map((c) => {
          const pascal = c.charAt(0).toUpperCase() + c.slice(1);
          return [`./components/${pascal}`, `./components/${pascal}/${pascal}.json`];
        }),
      ),
    },
    files: ["dist", "tokens", "components", "CHANGELOG.md"],
    scripts: {
      build: "tsc",
      prepublishOnly: "npm run build",
    },
    devDependencies: {
      "@types/react": "^18.0.0",
      "@types/react-dom": "^18.0.0",
      typescript: "^5.0.0",
    },
    peerDependencies: {
      react: ">=17.0.0",
      "react-dom": ">=17.0.0",
    },
    peerDependenciesMeta: {
      react: { optional: false },
      "react-dom": { optional: false },
    },
    engines: {
      node: ">=18.0.0",
    },
    dsforge: {
      generatedBy: "dsforge",
      configVersion: config.meta.version,
      preset: config.meta.preset ?? "comfortable",
      components: componentNames,
      themes: [] as string[],
    },
  };

  return JSON.stringify(pkg, null, 2);
}

// ─── tsconfig.json (for the generated package) ───────────────────────────────

export function generateTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2020", "DOM"],
        outDir: "./dist",
        rootDir: ".",
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        jsx: "react-jsx",
      },
      include: ["index.ts", "components/**/*"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  );
}

// ─── README.md ────────────────────────────────────────────────────────────────

export function generateReadme(
  config: DesignSystemConfig,
  componentNames: string[],
): string {
  const scope = config.meta.npmScope ?? "@myorg";
  const pkgName = `${scope}/${config.meta.name}`;
  const themeNames = ["light", "dark"]; // populated at call site if needed

  return `# ${config.meta.name}

> ${config.meta.description ?? "A design system generated by dsforge."}

[![npm version](https://badge.fury.io/js/${encodeURIComponent(pkgName)}.svg)](https://www.npmjs.com/package/${pkgName})

---

## Installation

\`\`\`bash
npm install ${pkgName}
\`\`\`

## Quick start

\`\`\`tsx
// 1. Import base tokens (once, in your app root)
import "${pkgName}/tokens/base.css";
import "${pkgName}/tokens/light.css";

// 2. Wrap your app
import { ThemeProvider, Button } from "${pkgName}";

function App() {
  return (
    <ThemeProvider theme="light">
      <Button variant="primary" aria-label="Get started">
        Get started
      </Button>
    </ThemeProvider>
  );
}
\`\`\`

## Components

${componentNames
  .map(
    (c) => {
      const pascal = c.charAt(0).toUpperCase() + c.slice(1);
      return `- **${pascal}** — see \`components/${pascal}/${pascal}.json\` for props and usage`;
    },
  )
  .join("\n")}

## Themes

${themeNames.map((t) => `- \`${t}\` — import \`${pkgName}/tokens/${t}.css\``).join("\n")}

### Theme switching

\`\`\`tsx
import { useTheme } from "${pkgName}";

function ThemeToggle() {
  const { theme, setTheme } = useTheme();
  return (
    <button onClick={() => setTheme(theme === "light" ? "dark" : "light")}>
      Toggle theme
    </button>
  );
}
\`\`\`

## Using with Tailwind

\`\`\`js
// tailwind.config.js
const ds = require("${pkgName}/tailwind");
module.exports = {
  theme: { extend: ds },
};
\`\`\`

## Without React (CSS tokens only)

\`\`\`html
<link rel="stylesheet" href="node_modules/${pkgName}/tokens/base.css" />
<link rel="stylesheet" href="node_modules/${pkgName}/tokens/light.css" />

<button class="my-button">Click me</button>

<style>
  .my-button {
    background: var(--color-action);
    color: var(--color-text-inverse);
    border-radius: var(--radius-md);
    padding: var(--component-padding-sm) var(--component-padding-md);
  }
</style>
\`\`\`

## Token customization

All design tokens are defined in \`design-system.config.json\`. After editing,
run \`dsforge generate\` to regenerate the package.

\`\`\`json
// design-system.config.json (excerpt)
{
  "tokens": {
    "global": {
      "color-brand-500": "#2563eb"
    },
    "semantic": {
      "color-action": "{global.color-brand-500}"
    }
  }
}
\`\`\`

Token references use \`{tier.name}\` syntax to alias values across tiers:
global → semantic → component. Changing a global value propagates through
every semantic and component token that references it.

## AI tool integration

Each component ships with a machine-readable JSON contract (e.g. \`components/Button/Button.json\`).
AI coding assistants (Copilot, Cursor, Claude Code) can read these to
generate UI that respects your governance rules automatically.

---

Generated by [dsforge](https://github.com/nghitrum/dsforge) v${config.meta.version}.
`;
}

// ─── CHANGELOG seed ──────────────────────────────────────────────────────────

export function generateChangelog(config: DesignSystemConfig): string {
  const date = new Date().toISOString().slice(0, 10);
  return `# Changelog

All notable changes to \`${config.meta.name}\` are documented here.
Format follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).

## [${config.meta.version}] — ${date}

### Added

- Initial release generated by dsforge
- Components: see \`metadata/index.json\` for full list
- Token architecture: global → semantic → component (3-tier)
- Themes: light, dark
- CSS custom property output for all tokens
- Tailwind theme extension
- AI-consumable metadata per component

---

_To add a new entry: run \`dsforge diff --from <prev-version>\` and paste the output here._
`;
}
