/**
 * ThemeProvider + component barrel index generator.
 *
 * Generates:
 *   ThemeProvider.tsx — React context-based theme switcher
 *   index.ts          — barrel export of all components
 */

import type { DesignSystemConfig } from "../../types/index";

// ─── ThemeProvider ────────────────────────────────────────────────────────────

export function generateThemeProvider(config: DesignSystemConfig): string {
  const themeNames = Object.keys(config.themes ?? { light: {}, dark: {} });
  const defaultTheme = themeNames.includes("light")
    ? "light"
    : (themeNames[0] ?? "light");
  const themeType = themeNames.map((t) => `"${t}"`).join(" | ");

  return `/**
 * ThemeProvider — ${config.meta.name}
 *
 * Applies the active theme by setting data-theme on the root element.
 * Consumers wrap their app (or a subtree) in ThemeProvider.
 *
 * Usage:
 *   import "@${config.meta.name}/tokens/base.css";
 *   import "@${config.meta.name}/tokens/light.css";  // or dark.css
 *   import { ThemeProvider } from "@${config.meta.name}";
 *
 *   <ThemeProvider theme="light">
 *     <App />
 *   </ThemeProvider>
 */

import React from "react";

// ─── Types ────────────────────────────────────────────────────────────────────

export type ThemeName = ${themeType};

export interface ThemeContextValue {
  theme: ThemeName;
  setTheme: (theme: ThemeName) => void;
}

export interface ThemeProviderProps {
  /** Initial theme. Defaults to "${defaultTheme}". */
  theme?: ThemeName;
  /** Called when setTheme is invoked — use to persist theme preference. */
  onThemeChange?: (theme: ThemeName) => void;
  children: React.ReactNode;
}

// ─── Context ──────────────────────────────────────────────────────────────────

export const ThemeContext = React.createContext<ThemeContextValue>({
  theme: "${defaultTheme}",
  setTheme: () => undefined,
});

/**
 * Hook to read and change the current theme.
 * Must be used inside a <ThemeProvider>.
 */
export function useTheme(): ThemeContextValue {
  return React.useContext(ThemeContext);
}

// ─── Provider ─────────────────────────────────────────────────────────────────

export function ThemeProvider({
  theme: initialTheme = "${defaultTheme}",
  onThemeChange,
  children,
}: ThemeProviderProps) {
  const [theme, setThemeState] = React.useState<ThemeName>(initialTheme);

  React.useEffect(() => {
    setThemeState(initialTheme);
  }, [initialTheme]);

  const setTheme = React.useCallback(
    (next: ThemeName) => {
      setThemeState(next);
      onThemeChange?.(next);
    },
    [onThemeChange],
  );

  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      <div data-theme={theme} style={{ display: "contents" }}>
        {children}
      </div>
    </ThemeContext.Provider>
  );
}
`;
}

// ─── Barrel index ─────────────────────────────────────────────────────────────

export function generateComponentIndex(
  config: DesignSystemConfig,
  componentNames: string[],
): string {
  const lines: string[] = [
    `/**`,
    ` * ${config.meta.name} — component library`,
    ` * Generated by dsforge v${config.meta.version}. Do not edit manually.`,
    ` *`,
    ` * Usage:`,
    ` *   import { Button, Input, Card, ThemeProvider } from "${config.meta.npmScope ?? "@myorg"}/${config.meta.name}";`,
    ` */`,
    "",
  ];

  // Re-export components
  for (const name of componentNames) {
    lines.push(`export * from "./${name}";`);
  }

  // Re-export ThemeProvider
  lines.push(`export * from "./ThemeProvider";`);
  lines.push("");

  return lines.join("\n");
}
