name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Bump version
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          npm version patch -m "chore: bump version to %s [skip ci]"
          git push

      - run: npm publish
